'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Zuken.E3.HarnessAnalyzer.Settings.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die FLY 0.5;0.5;9;4.45
        '''FLY 0.75;0.75;12;6.675
        '''FLY 1;1;15;8.9
        '''FLY 1.5;1.5;20;13.35
        '''FLY 2;2;26;17.8
        '''FLY 2.5;2.5;32;22.25
        '''FLY 3;3;38;26.7
        '''FLY 4;4;49;35.6
        '''FLY 6;6;69;53.4
        '''FLY 10;10;113;89
        '''FLY 16;16;181;142.4
        '''FLY 25;25;288;222.5
        '''FLY 35;35;361;311.5
        '''FLY 2;40;438;356
        '''FLY 50;50;521;445
        '''FLY 70;70;716;623
        '''FLY 95;95;918;845.5
        '''FLY 120;120;1220;1068
        '''FLRY-A 0.22;0.22;3;1.958
        '''FLRY-A 0.35;0.35;5;3.115
        '''FLRY-A 0.5;0.5;7;4.45
        '''FLRY-A 0.75;0.75;9;6.675
        '''FLRY-A 1;1;11;8.9
        '''FLRY-A 1.5;1.5;16;13.35
        '''FLRY-A 2;2;22; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property DefaultEntriesWeightSettings() As String
            Get
                Return ResourceManager.GetString("DefaultEntriesWeightSettings", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
