'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ErrorStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Zuken.E3.HarnessAnalyzer.ErrorStrings", GetType(ErrorStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please select valid wires. Selected wires aren&apos;t  adjacent.  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AdjacentWireVDrawUserControl_SelectionError() As String
            Get
                Return ResourceManager.GetString("AdjacentWireVDrawUserControl_SelectionError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Calculation was aborted internally (not possible by unknonwn reason) ! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CalculationWasAbortedInternallyNotPossibleByUnknonwnReason() As String
            Get
                Return ResourceManager.GetString("CalculationWasAbortedInternallyNotPossibleByUnknonwnReason", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Can&apos;t resolve harness configuration: not found in current document ! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CanTResolveHarnessConfigurationNotFoundInCurrentDocument() As String
            Get
                Return ResourceManager.GetString("CanTResolveHarnessConfigurationNotFoundInCurrentDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unexpected Error while loading comparable-property differences: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CompareForm_UnExpectedErrorGettingDifferences() As String
            Get
                Return ResourceManager.GetString("CompareForm_UnExpectedErrorGettingDifferences", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Can&apos;t load vehicle model: vehicle model directory &quot;{0}&quot; does not exist! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property D3D_CarModelDirectoryIsNotFound() As String
            Get
                Return ResourceManager.GetString("D3D_CarModelDirectoryIsNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Can&apos;t load vehicle model: vehicle model directory is not set! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property D3D_CarModelDirectoryIsNotSet() As String
            Get
                Return ResourceManager.GetString("D3D_CarModelDirectoryIsNotSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Can&apos;t load vehicle model: vehicle model file &quot;{0}&quot; does not exist in &quot;{1}&quot; ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property D3D_CarModelDoesNotExistIn() As String
            Get
                Return ResourceManager.GetString("D3D_CarModelDoesNotExistIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while recalculating bundles: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property D3D_Error_RecalculateBundles() As String
            Get
                Return ResourceManager.GetString("D3D_Error_RecalculateBundles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error ({0}) exporting model file &quot;{1}&quot;. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property D3D_ErrorExportingModel() As String
            Get
                Return ResourceManager.GetString("D3D_ErrorExportingModel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error ({0}) saving transformation file &quot;{1}&quot;. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property D3D_ErrorSavingTransformationFile() As String
            Get
                Return ResourceManager.GetString("D3D_ErrorSavingTransformationFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Update entity &quot;{0}&quot; has failed: &quot;{1}&quot;. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property D3D_ErrorUpdatingEntity() As String
            Get
                Return ResourceManager.GetString("D3D_ErrorUpdatingEntity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &quot;{0}&quot; is not a valid vehicle transformation file! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property D3D_NotATransformationFile() As String
            Get
                Return ResourceManager.GetString("D3D_NotATransformationFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;Unknown&gt; ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property D3D_UnknownEntity() As String
            Get
                Return ResourceManager.GetString("D3D_UnknownEntity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while exporting data tables to Excel!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocStatMachine_ErrorExportExcel_Msg() As String
            Get
                Return ResourceManager.GetString("DocStatMachine_ErrorExportExcel_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while exporting: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocStatMachine_ErrorExportMsg() As String
            Get
                Return ResourceManager.GetString("DocStatMachine_ErrorExportMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while trying to import selected graphical data compare result information file!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocStatMachine_ErrorImportGraphCompResultInfo_Msg() As String
            Get
                Return ResourceManager.GetString("DocStatMachine_ErrorImportGraphCompResultInfo_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Some errors/warnings occurred during import of memolist! See log for further information. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocStatMachine_ErrorImportMemolist_Msg() As String
            Get
                Return ResourceManager.GetString("DocStatMachine_ErrorImportMemolist_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while trying to import selected memolist file!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocStatMachine_ErrorImportMemolistFile_Msg() As String
            Get
                Return ResourceManager.GetString("DocStatMachine_ErrorImportMemolistFile_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Some errors/warnings occurred during import of QM stamp information! See log for further information. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocStatMachine_ErrorImportQMStamps_Msg() As String
            Get
                Return ResourceManager.GetString("DocStatMachine_ErrorImportQMStamps_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while trying to import selected QM stamp information file!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocStatMachine_ErrorImportQMStampsFile_Msg() As String
            Get
                Return ResourceManager.GetString("DocStatMachine_ErrorImportQMStampsFile_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Some errors/warnings occurred during import of redlining information! See log for further information. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocStatMachine_ErrorImportRedlining_Msg() As String
            Get
                Return ResourceManager.GetString("DocStatMachine_ErrorImportRedlining_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while trying to import selected redlining information file!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocStatMachine_ErrorImportRedliningFile_Msg() As String
            Get
                Return ResourceManager.GetString("DocStatMachine_ErrorImportRedliningFile_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while trying to import selected technical data compare result information file!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocStatMachine_ErrorImportTechCompResultInfo_Msg() As String
            Get
                Return ResourceManager.GetString("DocStatMachine_ErrorImportTechCompResultInfo_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while trying to import selected ultrasonic splice - terminal distance mapping file!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocStatMachine_ErrorImportUltrasonicSpliceTerminalDistanceMappingFile_Msg() As String
            Get
                Return ResourceManager.GetString("DocStatMachine_ErrorImportUltrasonicSpliceTerminalDistanceMappingFile_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while loading selected graphical data compare result information file! Possible harness part number/version mismatch! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocStatMachine_ErrorLoadGraphCompResultInfo_Msg() As String
            Get
                Return ResourceManager.GetString("DocStatMachine_ErrorLoadGraphCompResultInfo_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while loading selected memolist file!{0}{1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocStatMachine_ErrorLoadMemolistFile_Msg() As String
            Get
                Return ResourceManager.GetString("DocStatMachine_ErrorLoadMemolistFile_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error occurred during load of document ribbon menu!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocStatMachine_ErrorLoadMenu_Msg() As String
            Get
                Return ResourceManager.GetString("DocStatMachine_ErrorLoadMenu_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while loading selected QM stamp information file!{0}{1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocStatMachine_ErrorLoadQMStampsFile_Msg() As String
            Get
                Return ResourceManager.GetString("DocStatMachine_ErrorLoadQMStampsFile_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while loading selected redlining information file!{0}{1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocStatMachine_ErrorLoadRedliningFile_Msg() As String
            Get
                Return ResourceManager.GetString("DocStatMachine_ErrorLoadRedliningFile_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while loading selected technical data compare result information file! Possible harness part number/version mismatch! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocStatMachine_ErrorLoadTechCompResultInfo_Msg() As String
            Get
                Return ResourceManager.GetString("DocStatMachine_ErrorLoadTechCompResultInfo_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Either column &apos;TerminalPartNumber&apos; or column &apos;MinDistance&apos; in Excel worksheet is missing! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocStatMachine_ErrorLoadUltrasonicSpliceTerminalDistanceMappingFile_Excel() As String
            Get
                Return ResourceManager.GetString("DocStatMachine_ErrorLoadUltrasonicSpliceTerminalDistanceMappingFile_Excel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while loading selected ultrasonic splice - terminal distance mapping file!{0}{1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocStatMachine_ErrorLoadUltrasonicSpliceTerminalDistanceMappingFile_Msg() As String
            Get
                Return ResourceManager.GetString("DocStatMachine_ErrorLoadUltrasonicSpliceTerminalDistanceMappingFile_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Data schema validation for &apos;{0}&apos; failed! Please see information in logging window for further details. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocStatMachine_ErrorSchemaValidation_Msg() As String
            Get
                Return ResourceManager.GetString("DocStatMachine_ErrorSchemaValidation_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die RegEx pattern defined in the general settings configuration file isn&apos;t valid! Use default pattern instead. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocStatMachine_RegExForGenSettingsConfigInvalid_Msg() As String
            Get
                Return ResourceManager.GetString("DocStatMachine_RegExForGenSettingsConfigInvalid_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while import harness or unsupported DSI version! Please check log and/or your DSI file if the file version property is &apos;10&apos;, &apos;11&apos; or &apos;12&apos;. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DSIImport_ErrorHarnessOrUnsupportedVersion_Msg() As String
            Get
                Return ResourceManager.GetString("DSIImport_ErrorHarnessOrUnsupportedVersion_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while importing cable &apos;{0}&apos; information from DSI file: {1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DSIImport_ErrorImportCable() As String
            Get
                Return ResourceManager.GetString("DSIImport_ErrorImportCable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while importing component &apos;{0}&apos; information from DSI file: {1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DSIImport_ErrorImportComponent() As String
            Get
                Return ResourceManager.GetString("DSIImport_ErrorImportComponent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while importing harness &apos;{0}&apos; information from DSI file: {1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DSIImport_ErrorImportHarness() As String
            Get
                Return ResourceManager.GetString("DSIImport_ErrorImportHarness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while importing wire through nodes &apos;{0}&apos; information from DSI file: {1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DSIImport_ErrorImportRouting() As String
            Get
                Return ResourceManager.GetString("DSIImport_ErrorImportRouting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while importing segment &apos;{0}&apos; information from DSI file: {1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DSIImport_ErrorImportSegment() As String
            Get
                Return ResourceManager.GetString("DSIImport_ErrorImportSegment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while importing wire &apos;{0}&apos; information from DSI file: {1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DSIImport_ErrorImportWire() As String
            Get
                Return ResourceManager.GetString("DSIImport_ErrorImportWire", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while importing branch insulation &apos;{0}&apos; information from DSI file: {1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DSIImport_ErrorImportWireProtection() As String
            Get
                Return ResourceManager.GetString("DSIImport_ErrorImportWireProtection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Missing connector reference while importing cavity &apos;{0}&apos; information from DSI file. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DSIImport_WarningMissingConnectorReference() As String
            Get
                Return ResourceManager.GetString("DSIImport_WarningMissingConnectorReference", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Skipped import of branch insulation from DSI file with start node &apos;{0}&apos;: End node missing, might be a spot/breakout tape. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DSIImport_WarningMissingEndNode() As String
            Get
                Return ResourceManager.GetString("DSIImport_WarningMissingEndNode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cannot create connection while importing wire &apos;{0}&apos; information form DSI file: missing start and/or end node reference. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DSIImport_WarningMissingNodeReference() As String
            Get
                Return ResourceManager.GetString("DSIImport_WarningMissingNodeReference", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Errors happened while initializing (creating) appearances, proceeding with only in-memory-use ! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorInitCreatingAppearances() As String
            Get
                Return ResourceManager.GetString("ErrorInitCreatingAppearances", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Directory &quot;{0}&quot; does not exist! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property GeneralSettings_DirectoryNotFound() As String
            Get
                Return ResourceManager.GetString("GeneralSettings_DirectoryNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error setting filter in tab &quot;{0}&quot; to grid (new filtering is not available) ! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InformationHub_ErrorSetFilter() As String
            Get
                Return ResourceManager.GetString("InformationHub_ErrorSetFilter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die A borrowed license might have expired or{0}{1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InitMng_BorrowedLicExpired_Msg() As String
            Get
                Return ResourceManager.GetString("InitMng_BorrowedLicExpired_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die LmBorrow ({0}) not found! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InitMng_BorrowNotFound_Msg() As String
            Get
                Return ResourceManager.GetString("InitMng_BorrowNotFound_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error reading borrowed license: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InitMng_ErrorReadLic_Msg() As String
            Get
                Return ResourceManager.GetString("InitMng_ErrorReadLic_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The commandline processor needs to be initialized before the licensing system! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InitMng_InitCmdLine_Msg() As String
            Get
                Return ResourceManager.GetString("InitMng_InitCmdLine_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unit component with id &quot;{0}&quot; not found in kbl! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property KBL_UnitComponentIdNotFoundInKbl() As String
            Get
                Return ResourceManager.GetString("KBL_UnitComponentIdNotFoundInKbl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Could not authenticate your license. Error: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LicenseAccess_ErrorAuth_Msg() As String
            Get
                Return ResourceManager.GetString("LicenseAccess_ErrorAuth_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die HCV or DSI/KBL document with same name already opened! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_DocAlreadyOpened_Msg() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_DocAlreadyOpened_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error occurred during creation of application menu tools!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_ErrorCreatingApplicationMenuTools() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_ErrorCreatingApplicationMenuTools", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error occurred during creation of Home tabs!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_ErrorCreatingHomeTabs() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_ErrorCreatingHomeTabs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error occurred during creation of hom tab tools!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_ErrorCreatingHomeTabTools() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_ErrorCreatingHomeTabTools", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error occurred during creation of Menu tabs!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_ErrorCreatingMenuTabs() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_ErrorCreatingMenuTabs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error occurred during creation of Quick access toolbar!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_ErrorCreatingQuickAccessToolbar() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_ErrorCreatingQuickAccessToolbar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error occurred during creation of settings tab tools!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_ErrorCreatingSettingsTabTools() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_ErrorCreatingSettingsTabTools", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error occurred during creation of Tutorials menu!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_ErrorCreatingTutorials() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_ErrorCreatingTutorials", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while exporting HCV document to DSI!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_ErrorExportDSI_Msg() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_ErrorExportDSI_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while exporting HCV document to Excel!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_ErrorExportExcel_Msg() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_ErrorExportExcel_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while exporting current drawing to the selected graphic file!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_ErrorExportGraphic_Msg() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_ErrorExportGraphic_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while exporting HCV document to kbl file!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_ErrorExportKbl_Msg() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_ErrorExportKbl_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while exporting HCV document to PDF file!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_ErrorExportPDF_Msg() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_ErrorExportPDF_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error occurred during extracting extended HCV file!{0}{1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_ErrorExtractHCV_Msg() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_ErrorExtractHCV_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while importing DSI file!{0}{1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_ErrorImportDSI_Msg() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_ErrorImportDSI_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error occurred during initialization of settings tabs!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_ErrorInitializeSettingsTab() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_ErrorInitializeSettingsTab", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while loading configuration file with entire car settings!{0}{1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_ErrorLoadEntireCarSettings_Msg() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_ErrorLoadEntireCarSettings_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error occurred during load of E³.HarnessAnalyzer ribbon menu!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_ErrorLoadMenu_Msg() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_ErrorLoadMenu_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while printing HCV document!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_ErrorPrintDoc_Msg() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_ErrorPrintDoc_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while saving HCV document!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_ErrorSaveHCV_Msg() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_ErrorSaveHCV_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while loading virtual inliner document &apos;{0}&apos;:{1}{2} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_ErrorWhileLoadingVirtualInlinerDocument_Msg() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_ErrorWhileLoadingVirtualInlinerDocument_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die HCV document with same name already opened! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_HCVAlreadyOpened_Msg() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_HCVAlreadyOpened_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die E³.HarnessAnalyzer helpfile could not be found in expected file location! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_HelpNotFound_Msg() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_HelpNotFound_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Valid license feature missing for opening DSI files! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_LicFeatMissingDSI_Msg() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_LicFeatMissingDSI_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Valid license feature missing for opening PlmXml files! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_LicFeatMissingPlmXml_Msg() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_LicFeatMissingPlmXml_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unknown problem while exporting current drawing to the selected graphic file! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_ProblemExportGraphic_Msg() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_ProblemExportGraphic_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Recent file &apos;{0}&apos; could not be found! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_RecentFileNotFound_Msg() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_RecentFileNotFound_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Warning, failed to load car transformation settings from xhcv: &apos;{0}&apos;. Remove corrupt settings from file ? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MainStatMachine_WarningDeserializationCarTransformationSettingsFailed_Msg() As String
            Get
                Return ResourceManager.GetString("MainStatMachine_WarningDeserializationCarTransformationSettingsFailed_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No wires have been selected! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property OverallConn_NoWiresSelected() As String
            Get
                Return ResourceManager.GetString("OverallConn_NoWiresSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error getting all printers from local print server: &quot;{0}&quot; ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Printing_ErrorRetrievingAllLocalPrinters() As String
            Get
                Return ResourceManager.GetString("Printing_ErrorRetrievingAllLocalPrinters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error getting all printers from local print server: &quot;Timeout (&gt; 1 Minute)&quot; ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Printing_ErrorRetrievingPrinterTimeout() As String
            Get
                Return ResourceManager.GetString("Printing_ErrorRetrievingPrinterTimeout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error happened while printing: {0}. (Reason could be that the page size is too big for the selected printer). Restart of this dialog could be needed now to ensure further printing. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Printing_ErrorWhilePrinting() As String
            Get
                Return ResourceManager.GetString("Printing_ErrorWhilePrinting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Maximum page height is {0} inch ! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Printing_MaxHeightExceedsInch() As String
            Get
                Return ResourceManager.GetString("Printing_MaxHeightExceedsInch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Maximum page height is {0} mm ! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Printing_MaxHeightExceedsMM() As String
            Get
                Return ResourceManager.GetString("Printing_MaxHeightExceedsMM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Maximum page width is {0} inch ! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Printing_MaxWidthExceedsInch() As String
            Get
                Return ResourceManager.GetString("Printing_MaxWidthExceedsInch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Maximum page width is {0} mm ! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Printing_MaxWidthExceedsMM() As String
            Get
                Return ResourceManager.GetString("Printing_MaxWidthExceedsMM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Coudn&apos;t update page format to &quot;{0}&quot; because it does not exist on the printer ({1}). Using custom format ! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Printing_MissingPageToCustomUpdate() As String
            Get
                Return ResourceManager.GetString("Printing_MissingPageToCustomUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Printing is not possible because there are no local printers availalbe on the system! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Printing_NoPrintersAvailable() As String
            Get
                Return ResourceManager.GetString("Printing_NoPrintersAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No Printer was selected! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Printing_NoPrinterWasSelected() As String
            Get
                Return ResourceManager.GetString("Printing_NoPrinterWasSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error accessing issue report file &quot;{0}&quot;! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property QM_ErrorAccessingIssueReportFile() As String
            Get
                Return ResourceManager.GetString("QM_ErrorAccessingIssueReportFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error on saving issue report to file &quot;{0}&quot; ({1}). ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property QM_ErrorSavingIssueReport() As String
            Get
                Return ResourceManager.GetString("QM_ErrorSavingIssueReport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Issue report file &quot;{0}&quot; is not valid! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property QM_InvalidIssueReportFile() As String
            Get
                Return ResourceManager.GetString("QM_InvalidIssueReportFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Stamp file &quot;{0}&quot; is not valid! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property QM_InvalidStampFile() As String
            Get
                Return ResourceManager.GetString("QM_InvalidStampFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Issue report file &quot;{0}&quot; does not exist! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property QM_IssueReportFileDoesNotExist() As String
            Get
                Return ResourceManager.GetString("QM_IssueReportFileDoesNotExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Issue report file does not contain any issues! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property QM_IssueReportFileEmpty() As String
            Get
                Return ResourceManager.GetString("QM_IssueReportFileEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Selected report file does not match the current document (Harness part numbers: &quot;{0}&quot;&lt;&gt;&quot;{1}&quot;). Do you really want to use this file? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property QM_IssuesReportFileNotMatching() As String
            Get
                Return ResourceManager.GetString("QM_IssuesReportFileNotMatching", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Defined maximum range is smaller than highest number of occurrences in the report file! Please use at least {0}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property QM_MaximumRangeColorTooLow() As String
            Get
                Return ResourceManager.GetString("QM_MaximumRangeColorTooLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please select an issue report file! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property QM_SelectIssueReportFile() As String
            Get
                Return ResourceManager.GetString("QM_SelectIssueReportFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please select a stamp file! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property QM_SelectStampFile() As String
            Get
                Return ResourceManager.GetString("QM_SelectStampFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Stamp file &quot;{0}&quot; does not exist! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property QM_StampFileDoesNotExist() As String
            Get
                Return ResourceManager.GetString("QM_StampFileDoesNotExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Initialization of search pattern failed!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SearchMachine_InitPatternFailed_Msg() As String
            Get
                Return ResourceManager.GetString("SearchMachine_InitPatternFailed_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please select a single valid wire path from source to target! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SelectedWireOrCoreVDrawUserControl_SelectionError() As String
            Get
                Return ResourceManager.GetString("SelectedWireOrCoreVDrawUserControl_SelectionError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while showing wizard: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TopologyCompare_ErrorShowingWizard() As String
            Get
                Return ResourceManager.GetString("TopologyCompare_ErrorShowingWizard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please select valid documents before starting with compare! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TopologyCompareSelectValidDocuments() As String
            Get
                Return ResourceManager.GetString("TopologyCompareSelectValidDocuments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Export failed ! Cannot be exported to excel .Check following Error {0} {1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property VoltageDropExport_ErrorOccurred() As String
            Get
                Return ResourceManager.GetString("VoltageDropExport_ErrorOccurred", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Export Error ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property VoltageDropExport_ErrorTitel() As String
            Get
                Return ResourceManager.GetString("VoltageDropExport_ErrorTitel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Knock-off length is too high, resulting wire length must not get negative! Maximum value:({0}) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WeightCalc_DeltaBiggerThanShortestLength() As String
            Get
                Return ResourceManager.GetString("WeightCalc_DeltaBiggerThanShortestLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while trying to retrieve material specification for &quot;{0}&quot;: {1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WeightCalc_ErrorRetrievingMaterialSpec() As String
            Get
                Return ResourceManager.GetString("WeightCalc_ErrorRetrievingMaterialSpec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Default length property &quot;{0}&quot; was not found! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WeightCalc_LengthNotFound() As String
            Get
                Return ResourceManager.GetString("WeightCalc_LengthNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Length must be equal or higher than {0}, because the resulting length must not get negative. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WeightCalc_LengthResultWouldBeZeroWithGivenLength() As String
            Get
                Return ResourceManager.GetString("WeightCalc_LengthResultWouldBeZeroWithGivenLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Material specification field &quot;{0}&quot; was not found in Cable! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WeightCalc_MaterialSpecFieldNotFoundInCable() As String
            Get
                Return ResourceManager.GetString("WeightCalc_MaterialSpecFieldNotFoundInCable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Material specification field &quot;{0}&quot; was not found in Core! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WeightCalc_MaterialSpecFieldNotFoundInCore() As String
            Get
                Return ResourceManager.GetString("WeightCalc_MaterialSpecFieldNotFoundInCore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Material specification field &quot;{0}&quot; was not found in Wire! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WeightCalc_MaterialSpecFieldNotFoundInWire() As String
            Get
                Return ResourceManager.GetString("WeightCalc_MaterialSpecFieldNotFoundInWire", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die To apply, a minimum length of {0} is required! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WeightCalc_MinimumLengthRequired() As String
            Get
                Return ResourceManager.GetString("WeightCalc_MinimumLengthRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No source (material specification or lookup) could be found for weight calculation! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WeightCalc_NoSourceMsg() As String
            Get
                Return ResourceManager.GetString("WeightCalc_NoSourceMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die A material specification regex ({0}) is not defined! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WeightCalc_RegexNothingError() As String
            Get
                Return ResourceManager.GetString("WeightCalc_RegexNothingError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The material specification regex &quot;{0}&quot; ({1}) is incorrect! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WeightCalc_RegexPatternError() As String
            Get
                Return ResourceManager.GetString("WeightCalc_RegexPatternError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Writing to file &quot;{0}&quot; failed with error &quot;{1}&quot; ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WritingToFileError() As String
            Get
                Return ResourceManager.GetString("WritingToFileError", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
