'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class GeneralSettingsFormStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Zuken.E3.HarnessAnalyzer.GeneralSettingsFormStrings", GetType(GeneralSettingsFormStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Add color code ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AddColor_InputBoxTitle() As String
            Get
                Return ResourceManager.GetString("AddColor_InputBoxTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Add bundle diameter range ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AddDiaRange_InputBoxTitle() As String
            Get
                Return ResourceManager.GetString("AddDiaRange_InputBoxTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Add eyelet identifier ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AddEyeletIdent_InputBoxPrompt() As String
            Get
                Return ResourceManager.GetString("AddEyeletIdent_InputBoxPrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Add inliner identifier ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AddInlIdent_InputBoxPrompt() As String
            Get
                Return ResourceManager.GetString("AddInlIdent_InputBoxPrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Add splice identifier ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AddSpliceIdent_InputBoxPrompt() As String
            Get
                Return ResourceManager.GetString("AddSpliceIdent_InputBoxPrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Add ultrasonic splice identifier ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AddUSSpliceIdent_InputBoxPrompt() As String
            Get
                Return ResourceManager.GetString("AddUSSpliceIdent_InputBoxPrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Color code ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ColorCode_ColCaption() As String
            Get
                Return ResourceManager.GetString("ColorCode_ColCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete the selected conditions of the {0}-identifier ? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ComponentIdentifierConditionsDeletePrompt() As String
            Get
                Return ResourceManager.GetString("ComponentIdentifierConditionsDeletePrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete the selected conditions of the {0}-identifiers ? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ComponentIdentifierMultipleConditionsDeletePrompt() As String
            Get
                Return ResourceManager.GetString("ComponentIdentifierMultipleConditionsDeletePrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Adding conditions for a standard identifier is not allowed! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ConditionForStandardIdentifierNotAllowed_Msg() As String
            Get
                Return ResourceManager.GetString("ConditionForStandardIdentifierNotAllowed_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Delete bundle diameter range {0} - {1}? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DelBundleDiaRange_Msg() As String
            Get
                Return ResourceManager.GetString("DelBundleDiaRange_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Delete wire color code &apos;{0}&apos;? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DelColorCode_Msg() As String
            Get
                Return ResourceManager.GetString("DelColorCode_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Delete entry ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Delete_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("Delete_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Delete eyelet identifier linked to KBL connector object property &apos;{0}&apos;? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DelEyeletIdent_Msg() As String
            Get
                Return ResourceManager.GetString("DelEyeletIdent_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Delete inliner identifier linked to KBL connector object property &apos;{0}&apos;? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DelInlIdent_Msg() As String
            Get
                Return ResourceManager.GetString("DelInlIdent_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Delete splice identifier linked to KBL connector object property &apos;{0}&apos;? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DelSpliceIdent_Msg() As String
            Get
                Return ResourceManager.GetString("DelSpliceIdent_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Delete ultrasonic splice identifier linked to KBL connector object property &apos;{0}&apos;? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DelUSSpliceIdent_Msg() As String
            Get
                Return ResourceManager.GetString("DelUSSpliceIdent_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Selected bundle diameter range has an invalid input format or already exists! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DiaHasInvalidFormat_Msg() As String
            Get
                Return ResourceManager.GetString("DiaHasInvalidFormat_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die English ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property EnglishLang_ListItem() As String
            Get
                Return ResourceManager.GetString("EnglishLang_ListItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Enter new color code: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property EnterColor_InputBoxPrompt() As String
            Get
                Return ResourceManager.GetString("EnterColor_InputBoxPrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Enter new bundle diameter range: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property EnterDiaRange_InputBoxPrompt() As String
            Get
                Return ResourceManager.GetString("EnterDiaRange_InputBoxPrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Recent file list successfully cleared! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FileListCleared_Msg() As String
            Get
                Return ResourceManager.GetString("FileListCleared_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die German ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property GermanLang_ListItem() As String
            Get
                Return ResourceManager.GetString("GermanLang_ListItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Identification criteria ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property IdentCriteria_ColCaption() As String
            Get
                Return ResourceManager.GetString("IdentCriteria_ColCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Only valid on inline connectors! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property IdentifierGroupSuffixEditOnlyInlinerAllowedErrorMessage() As String
            Get
                Return ResourceManager.GetString("IdentifierGroupSuffixEditOnlyInlinerAllowedErrorMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die KBL property name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property KBLPropName_ColCaption() As String
            Get
                Return ResourceManager.GetString("KBLPropName_ColCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Only Errors ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LogVerbosity_ErrorsOnly() As String
            Get
                Return ResourceManager.GetString("LogVerbosity_ErrorsOnly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Silent ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LogVerbosity_Silent() As String
            Get
                Return ResourceManager.GetString("LogVerbosity_Silent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Warnings and errors ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LogVerbosity_WarningsAndErrors() As String
            Get
                Return ResourceManager.GetString("LogVerbosity_WarningsAndErrors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Max. diameter [mm²] ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MaxDia_ColCaption() As String
            Get
                Return ResourceManager.GetString("MaxDia_ColCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Min. diameter [mm²] ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MinDia_ColCaption() As String
            Get
                Return ResourceManager.GetString("MinDia_ColCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die [Min. diameter here] - [Max. diameter here] ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MinMaxDia_InputBoxDefResp() As String
            Get
                Return ResourceManager.GetString("MinMaxDia_InputBoxDefResp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No further KBL connector object properties available for defining new identification criteria! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NoFurtherConnPropAvailable_Msg() As String
            Get
                Return ResourceManager.GetString("NoFurtherConnPropAvailable_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Not editable for type splice or eyelet! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NotEditableForSpliceOrEyeletMessage() As String
            Get
                Return ResourceManager.GetString("NotEditableForSpliceOrEyeletMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die physical length ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PhysicalLength() As String
            Get
                Return ResourceManager.GetString("PhysicalLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please close all opened documents to apply changes! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PleaseCloseAllOpenedDocumentsToApplyChange_Msg() As String
            Get
                Return ResourceManager.GetString("PleaseCloseAllOpenedDocumentsToApplyChange_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The  condition definition {0} is invalid! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RegExInvalid() As String
            Get
                Return ResourceManager.GetString("RegExInvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Reset color codes to their default values? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ResetColorCodes_Msg() As String
            Get
                Return ResourceManager.GetString("ResetColorCodes_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Reset component and inliner identifiers for schematics view to their default values? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ResetComponentIdent_Msg() As String
            Get
                Return ResourceManager.GetString("ResetComponentIdent_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Changing the UI language does not affect the data table appearance settings. Would you like to reset the data table settings? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ResetDataTableSettings_Msg() As String
            Get
                Return ResourceManager.GetString("ResetDataTableSettings_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Reset bundle diameters to their default ranges? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ResetDiaRanges_Msg() As String
            Get
                Return ResourceManager.GetString("ResetDiaRanges_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Reset inliner identifiers to their default values? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ResetInlIdent_Msg() As String
            Get
                Return ResourceManager.GetString("ResetInlIdent_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Reset ultrasonic splice identifiers to their default values? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ResetUSSpliceIdent_Msg() As String
            Get
                Return ResourceManager.GetString("ResetUSSpliceIdent_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please restart the application to apply all UI language changes. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RestartApp_Msg() As String
            Get
                Return ResourceManager.GetString("RestartApp_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Selected color code already exists! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SelColorExists_Msg() As String
            Get
                Return ResourceManager.GetString("SelColorExists_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Select available KBL connector object property: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SelKBLConn_InputBoxTitle() As String
            Get
                Return ResourceManager.GetString("SelKBLConn_InputBoxTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Use automatic tooltips ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property uckAutomaticTooltips() As String
            Get
                Return ResourceManager.GetString("uckAutomaticTooltips", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die virtual length ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property VirtualLength() As String
            Get
                Return ResourceManager.GetString("VirtualLength", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die MaxMoveTolerance ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MaxMoveTolerance() As String
            Get
                Return ResourceManager.GetString("MaxMoveTolerance", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
