'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class GraphicalCompareFormStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Zuken.E3.HarnessAnalyzer.GraphicalCompareFormStrings", GetType(GraphicalCompareFormStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Added ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Added() As String
            Get
                Return ResourceManager.GetString("Added", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Appearance ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Appearance_Class() As String
            Get
                Return ResourceManager.GetString("Appearance_Class", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Appearance; Move ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AppearanceMove_Class() As String
            Get
                Return ResourceManager.GetString("AppearanceMove_Class", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Approx. diff. metric: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ApprDiffMetric_CellValue() As String
            Get
                Return ResourceManager.GetString("ApprDiffMetric_CellValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Cancel_Text() As String
            Get
                Return ResourceManager.GetString("Cancel_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Compare result state of &apos;{0}&apos; from type &apos;{1}&apos; cannot be saved because an indentical graphical entry already exists. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CannotSaveResult_Msg() As String
            Get
                Return ResourceManager.GetString("CannotSaveResult_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Compare drawing graphics of HCV documents ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Caption() As String
            Get
                Return ResourceManager.GetString("Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Check all filtered compare results ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CheckAllResults_ButtonCaption() As String
            Get
                Return ResourceManager.GetString("CheckAllResults_ButtonCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Checked ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Checked_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("Checked_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Check selected compare result ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CheckSelResult_ButtonCaption() As String
            Get
                Return ResourceManager.GetString("CheckSelResult_ButtonCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Classification ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Classification_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("Classification_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Comment ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Comment_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("Comment_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Compare ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Compare_Text() As String
            Get
                Return ResourceManager.GetString("Compare_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Compare results ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CompareResults_GroupBoxCaption() As String
            Get
                Return ResourceManager.GetString("CompareResults_GroupBoxCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Compare signature ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CompSign_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("CompSign_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Deleted ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Deleted() As String
            Get
                Return ResourceManager.GetString("Deleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Delta X: {0}; Delta Y: {1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DeltaXY_CellValue() As String
            Get
                Return ResourceManager.GetString("DeltaXY_CellValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Details ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Details_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("Details_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Harness part numbers of selected HCV documents seem to be different! Check state progress will not be saved to reference HCV. Continue with the graphical compare process? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DifferentHarnessPartNumbers_Msg() As String
            Get
                Return ResourceManager.GetString("DifferentHarnessPartNumbers_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Diff. type ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DiffType_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("DiffType_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dimension ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Dimension_EntityType() As String
            Get
                Return ResourceManager.GetString("Dimension_EntityType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Entity index ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property EntityIndex_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("EntityIndex_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Undefined ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property EntityType_Undefined() As String
            Get
                Return ResourceManager.GetString("EntityType_Undefined", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error occurred while comparing graphical data: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorCompare_Msg() As String
            Get
                Return ResourceManager.GetString("ErrorCompare_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while exporting grid content to Excel!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorExportExcel_Msg() As String
            Get
                Return ResourceManager.GetString("ErrorExportExcel_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error occurred saving check state of compare result information in reference HCV file!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorSaveResult_Msg() As String
            Get
                Return ResourceManager.GetString("ErrorSaveResult_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Grid export to Excel has been cancelled! Please close the dialog once again... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportCancelled_Msg() As String
            Get
                Return ResourceManager.GetString("ExportCancelled_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Export compare result to Excel... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportExcel_Tooltip() As String
            Get
                Return ResourceManager.GetString("ExportExcel_Tooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Export compare results to Excel... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportExcelFile_Title() As String
            Get
                Return ResourceManager.GetString("ExportExcelFile_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Excel export successfully finished! Open created workbook? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportFinished_Msg() As String
            Get
                Return ResourceManager.GetString("ExportFinished_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Compare results (filtered by area) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FilterResults_GroupBoxCaption() As String
            Get
                Return ResourceManager.GetString("FilterResults_GroupBoxCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die From current view in dialog ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FromCurrentView_ButtonCaption() As String
            Get
                Return ResourceManager.GetString("FromCurrentView_ButtonCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die From reference drawing tab ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FromRefDrawingTab_ButtonCaption() As String
            Get
                Return ResourceManager.GetString("FromRefDrawingTab_ButtonCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Modified ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Modified() As String
            Get
                Return ResourceManager.GetString("Modified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Move ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Move_Class() As String
            Get
                Return ResourceManager.GetString("Move_Class", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die There is no compare drawing available for graphical compare for selected document. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NoCompareDrw_Msg() As String
            Get
                Return ResourceManager.GetString("NoCompareDrw_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Object name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ObjName_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("ObjName_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Object type ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ObjType_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("ObjType_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Redo previous action ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Redo_ButtonCaption() As String
            Get
                Return ResourceManager.GetString("Redo_ButtonCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Reference ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Reference_EntityType() As String
            Get
                Return ResourceManager.GetString("Reference_EntityType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Reference signature ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RefSign_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("RefSign_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Representation ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Representation_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("Representation_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Row count filtered/all: {0}/{1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RowCount_Label() As String
            Get
                Return ResourceManager.GetString("RowCount_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Save modified check state of compare result information in reference HCV? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SaveCompareResult_Msg() As String
            Get
                Return ResourceManager.GetString("SaveCompareResult_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Save modified check state of compare result information in reference HCV ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SaveCompareResult_Tooltip() As String
            Get
                Return ResourceManager.GetString("SaveCompareResult_Tooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die One or more warnings occurred while saving check state of compare result information in reference HCV file!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SaveWarning1_Msg() As String
            Get
                Return ResourceManager.GetString("SaveWarning1_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please refer to the log window for further detailed information. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SaveWarning2_Msg() As String
            Get
                Return ResourceManager.GetString("SaveWarning2_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Sync view center and zoom level with reference drawing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SyncViewCenter_Tooltip() As String
            Get
                Return ResourceManager.GetString("SyncViewCenter_Tooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Table ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Table_EntityType() As String
            Get
                Return ResourceManager.GetString("Table_EntityType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Table cell ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TableCell_EntityType() As String
            Get
                Return ResourceManager.GetString("TableCell_EntityType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Table row ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TableRow_EntityType() As String
            Get
                Return ResourceManager.GetString("TableRow_EntityType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die To be changed ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ToBeChanged_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("ToBeChanged_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Transformation ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Transformation_CellValue() As String
            Get
                Return ResourceManager.GetString("Transformation_CellValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Uncheck checked flag? Possible assigned comment will be deleted. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Uncheck_Msg() As String
            Get
                Return ResourceManager.GetString("Uncheck_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Uncheck all filtered compare results ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property UncheckAllResults_ButtonCaption() As String
            Get
                Return ResourceManager.GetString("UncheckAllResults_ButtonCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Uncheck all visible checked flags? Possible assigned comments will be deleted. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property UncheckAllVisible_Msg() As String
            Get
                Return ResourceManager.GetString("UncheckAllVisible_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Uncheck checked flag from selected object? Possible assigned comments will be deleted. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property UncheckFromSelected_Msg() As String
            Get
                Return ResourceManager.GetString("UncheckFromSelected_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Uncheck selected compare result ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property UncheckSelResult_ButtonCaption() As String
            Get
                Return ResourceManager.GetString("UncheckSelResult_ButtonCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Uncheck to be changed flag? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property UncheckToBeChangedFlag_Msg() As String
            Get
                Return ResourceManager.GetString("UncheckToBeChangedFlag_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Undo last action ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Undo_ButtonCaption() As String
            Get
                Return ResourceManager.GetString("Undo_ButtonCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Graphical compare results ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Worksheet_Name() As String
            Get
                Return ResourceManager.GetString("Worksheet_Name", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
