'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class GraphicalRedliningFormStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Zuken.E3.HarnessAnalyzer.GraphicalRedliningFormStrings", GetType(GraphicalRedliningFormStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die   Define base point of dimension in drawing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefBPDim_Label() As String
            Get
                Return ResourceManager.GetString("DefBPDim_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die   Define base point of text in drawing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefBPText_Label() As String
            Get
                Return ResourceManager.GetString("DefBPText_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die   Define center point of arc in drawing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefCPArc_Label() As String
            Get
                Return ResourceManager.GetString("DefCPArc_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die   Define center point of circle in drawing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefCPCircle_Label() As String
            Get
                Return ResourceManager.GetString("DefCPCircle_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die   Define end angle of arc in drawing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefEAngArc_Label() As String
            Get
                Return ResourceManager.GetString("DefEAngArc_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die   Define end corner of rectangle in drawing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefECRect_Label() As String
            Get
                Return ResourceManager.GetString("DefECRect_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die   Define end point of arrow line in drawing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefEPArrow_Label() As String
            Get
                Return ResourceManager.GetString("DefEPArrow_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die   Define end point of line in drawing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefEPLine_Label() As String
            Get
                Return ResourceManager.GetString("DefEPLine_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die   Define next vertex point of poyline in drawing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefNxtVertexPntPolyline_Label() As String
            Get
                Return ResourceManager.GetString("DefNxtVertexPntPolyline_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die   Define offset of dimension in drawing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefOffsetDim_Label() As String
            Get
                Return ResourceManager.GetString("DefOffsetDim_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die   Define radius of arc in drawing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefRadArc_Label() As String
            Get
                Return ResourceManager.GetString("DefRadArc_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die   Define radius of circle in drawing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefRadCircle_Label() As String
            Get
                Return ResourceManager.GetString("DefRadCircle_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die   Define rotation of text in drawing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefRotText_Label() As String
            Get
                Return ResourceManager.GetString("DefRotText_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die   Define reference point of dimension in drawing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefRPDim_Label() As String
            Get
                Return ResourceManager.GetString("DefRPDim_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die   Define start angle of arc in drawing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefSAngArc_Label() As String
            Get
                Return ResourceManager.GetString("DefSAngArc_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die   Define start corner of rectangle in drawing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefSCRect_Label() As String
            Get
                Return ResourceManager.GetString("DefSCRect_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die   Define start point of arrow line in drawing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefSPArrow_Label() As String
            Get
                Return ResourceManager.GetString("DefSPArrow_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die   Define start point of (poly)line in drawing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefSPLine_Label() As String
            Get
                Return ResourceManager.GetString("DefSPLine_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die   Define text string in drawing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefTxtString_Label() As String
            Get
                Return ResourceManager.GetString("DefTxtString_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while exporting graphical redlining to the selected graphic file!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorExportRedlining_Msg() As String
            Get
                Return ResourceManager.GetString("ErrorExportRedlining_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Graphical redlining successfully exported! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportRedliningSuccess_Msg() As String
            Get
                Return ResourceManager.GetString("ExportRedliningSuccess_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Export graphical redlining as... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportRedliningToFile_Title() As String
            Get
                Return ResourceManager.GetString("ExportRedliningToFile_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Failed to load graphical redlining! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FailedLoadRedlining_Msg() As String
            Get
                Return ResourceManager.GetString("FailedLoadRedlining_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Problem occurred while exporting graphical redlining! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProblemExportRedlining_Msg() As String
            Get
                Return ResourceManager.GetString("ProblemExportRedlining_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Save changes? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SaveChanges_Msg() As String
            Get
                Return ResourceManager.GetString("SaveChanges_Msg", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
