'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class GridAppearanceFormStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Zuken.E3.HarnessAnalyzer.GridAppearanceFormStrings", GetType(GridAppearanceFormStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Data table settings ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Caption() As String
            Get
                Return ResourceManager.GetString("Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Change column caption... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ChangeCaption_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("ChangeCaption_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Change data table column caption (Original KBL property name: {0}) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ChangeCaption_InputBoxPrompt() As String
            Get
                Return ResourceManager.GetString("ChangeCaption_InputBoxPrompt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Collapse selected ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CollapseSelection_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("CollapseSelection_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Data table column &apos;{0}&apos; ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DataTableColumn_InputBoxTitle() As String
            Get
                Return ResourceManager.GetString("DataTableColumn_InputBoxTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error on deleting appearance directory: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorDeletingDirectory() As String
            Get
                Return ResourceManager.GetString("ErrorDeletingDirectory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Defined column caption exceeds maximum allowed length! Maximum column name length is 50 characters. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorMaxCaptionLength_Msg() As String
            Get
                Return ResourceManager.GetString("ErrorMaxCaptionLength_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Expand selected ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExpandSelection_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("ExpandSelection_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Loading and initializing of data table settings tree failed!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LoadTreeFailed_Msg() As String
            Get
                Return ResourceManager.GetString("LoadTreeFailed_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Reset to default data table settings? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ResetDefault_Msg() As String
            Get
                Return ResourceManager.GetString("ResetDefault_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Select all ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SelectAll_CtxMnu_Caption() As String
            Get
                Return ResourceManager.GetString("SelectAll_CtxMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Toggle compare ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ToggleComparable_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("ToggleComparable_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Toggle find inclusion ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ToggleFinIncl_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("ToggleFinIncl_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Toggle display in 3D Popup ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ToggleShowIn3D_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("ToggleShowIn3D_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Toggle visibility ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ToggleVisibility_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("ToggleVisibility_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
