'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class InformationHubStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Zuken.E3.HarnessAnalyzer.InformationHubStrings", GetType(InformationHubStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abbreviation ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Abbreviation_Caption() As String
            Get
                Return ResourceManager.GetString("Abbreviation_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die |Accessory/Fixing name: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AccFixName_ExcelComment() As String
            Get
                Return ResourceManager.GetString("AccFixName_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die [ADDED]  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Added_CellValue() As String
            Get
                Return ResourceManager.GetString("Added_CellValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Added ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Added() As String
            Get
                Return ResourceManager.GetString("Added", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0}Added -&gt; {1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Added_TooltipPart() As String
            Get
                Return ResourceManager.GetString("Added_TooltipPart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0}Added -&gt; {1} {2} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Added2_TooltipPart() As String
            Get
                Return ResourceManager.GetString("Added2_TooltipPart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0}Added -&gt; Type: {1} | Value: {2} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Added3_TooltipPart() As String
            Get
                Return ResourceManager.GetString("Added3_TooltipPart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Add. extremities ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AddExtremities_Caption() As String
            Get
                Return ResourceManager.GetString("AddExtremities_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Additional length information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AddLengthInfo_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("AddLengthInfo_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Add selected object(s) to memolist ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AddToMemList_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("AddToMemList_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alias id: {0} | Scope: {1} | Description: {2} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AliasId_TooltipPart() As String
            Get
                Return ResourceManager.GetString("AliasId_TooltipPart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alias identification ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AliasIds_Caption() As String
            Get
                Return ResourceManager.GetString("AliasIds_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die      Approver department:{0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ApprDep_ExcelComment() As String
            Get
                Return ResourceManager.GetString("ApprDep_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die      Approver name:{0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ApprName_ExcelComment() As String
            Get
                Return ResourceManager.GetString("ApprName_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die |Area: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Area_ExcelComment() As String
            Get
                Return ResourceManager.GetString("Area_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Assigned modules ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AssignedModules_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("AssignedModules_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Calculate distance ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CalcDist_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("CalcDist_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Calculated distance between selected objects:{0}{0}Physical: {1} {2}{0}Virtual: {3} {4} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CalcDist_Msg() As String
            Get
                Return ResourceManager.GetString("CalcDist_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Calculate module weight(s)... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CalcModWeight_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("CalcModWeight_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Calculate total length ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CalcTotLength_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("CalcTotLength_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Calculated total length of selected segments:{0}{0}Physical: {1} {2}{0}Virtual: {3} {4} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CalcTotLength_Msg() As String
            Get
                Return ResourceManager.GetString("CalcTotLength_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Calculate wire resistance... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CalcWirRes_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("CalcWirRes_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Calculate wire weight(s)... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CalcWirWeight_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("CalcWirWeight_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Car classification level 2 ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CarClassLvl2_Caption() As String
            Get
                Return ResourceManager.GetString("CarClassLvl2_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Car classification level 3 ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CarClassLvl3_Caption() As String
            Get
                Return ResourceManager.GetString("CarClassLvl3_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Car classification level 4 ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CarClassLvl4_Caption() As String
            Get
                Return ResourceManager.GetString("CarClassLvl4_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Change ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Change_Caption() As String
            Get
                Return ResourceManager.GetString("Change_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Id: {0} | Description: {1} | Change request: {2} | Change date: {3} | Resp. designer: {4} | Designer department: {5} | Approver name: {6} | Approver department: {7} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Change_TooltipPart() As String
            Get
                Return ResourceManager.GetString("Change_TooltipPart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die      Change date:{0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ChangeDate_ExcelComment() As String
            Get
                Return ResourceManager.GetString("ChangeDate_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Changed elements ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ChangedElements_Caption() As String
            Get
                Return ResourceManager.GetString("ChangedElements_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die      Change level:{0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ChangeLvl_ExcelComment() As String
            Get
                Return ResourceManager.GetString("ChangeLvl_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die      Change request:{0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ChangeReq_ExcelComment() As String
            Get
                Return ResourceManager.GetString("ChangeReq_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Check comment ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CheckComment_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("CheckComment_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Checked ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Checked_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("Checked_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Checked by ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CheckedBy_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("CheckedBy_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Check result ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CheckResult_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("CheckResult_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Child object(s) contains one or more validity check result(s)! Expand row for more information! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ChildObjectContainsOneOrMoreValidityCheckResults_TooltipText() As String
            Get
                Return ResourceManager.GetString("ChildObjectContainsOneOrMoreValidityCheckResults_TooltipText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Class ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Class_Caption() As String
            Get
                Return ResourceManager.GetString("Class_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Classification ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Classification_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("Classification_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Clear all filters on all tabs ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ClearAllFilters_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("ClearAllFilters_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Clear all filters on this tab ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ClearFilters_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("ClearFilters_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Clear marked object(s) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ClearMarkedObjs_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("ClearMarkedObjs_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Collapse all rows ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CollapseAll_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("CollapseAll_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Comment ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Comment_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("Comment_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Company name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CompanyName_Caption() As String
            Get
                Return ResourceManager.GetString("CompanyName_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Comparable differences ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ComparableWorksheet_Name() As String
            Get
                Return ResourceManager.GetString("ComparableWorksheet_Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die [COMP.] ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Compare_CellValue() As String
            Get
                Return ResourceManager.GetString("Compare_CellValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Compare document:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CompDoc1_TooltipPart() As String
            Get
                Return ResourceManager.GetString("CompDoc1_TooltipPart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Compare document: - ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CompDoc2_TooltipPart() As String
            Get
                Return ResourceManager.GetString("CompDoc2_TooltipPart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die |Cavity number: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CompPinMapCavNumber_ExcelComment() As String
            Get
                Return ResourceManager.GetString("CompPinMapCavNumber_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die |Connected contact points: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CompPinMapContactPoint_ExcelComment() As String
            Get
                Return ResourceManager.GetString("CompPinMapContactPoint_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Component pin number: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CompPinMapPinNumber_ExcelComment() As String
            Get
                Return ResourceManager.GetString("CompPinMapPinNumber_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Confirmation ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Confirmation_RedliningType() As String
            Get
                Return ResourceManager.GetString("Confirmation_RedliningType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Content ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Content_Caption() As String
            Get
                Return ResourceManager.GetString("Content_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Controlled components by module ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ControlledComponents_Caption() As String
            Get
                Return ResourceManager.GetString("ControlledComponents_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Copyright note ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CopyrightNote_Caption() As String
            Get
                Return ResourceManager.GetString("CopyrightNote_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Created by ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CreatedBy_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("CreatedBy_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die      Creating system:{0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CreatingSys_ExcelComment() As String
            Get
                Return ResourceManager.GetString("CreatingSys_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cross section area information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CSAInfo_Caption() As String
            Get
                Return ResourceManager.GetString("CSAInfo_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Controlled components ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CtrlComps_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("CtrlComps_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die      Data format:{0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DataFormat_ExcelComment() As String
            Get
                Return ResourceManager.GetString("DataFormat_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Date of check ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DateOfCheck_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("DateOfCheck_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Date of creation ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DateOfCreation_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("DateOfCreation_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Default cable length type &apos;{0}&apos; not found in current document! Please change your settings. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefCabLengthTypeNotFound_Msg() As String
            Get
                Return ResourceManager.GetString("DefCabLengthTypeNotFound_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Default cable length type &apos;{0}&apos; and default wire length type &apos;{1}&apos; were both not found in current document! Please change your settings. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefWireAndCableLengthTypeNotFound_Msg() As String
            Get
                Return ResourceManager.GetString("DefWireAndCableLengthTypeNotFound_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Default wire length type &apos;{0}&apos; not found in current document! Please change your settings. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefWirLengthTypeNotFound_Msg() As String
            Get
                Return ResourceManager.GetString("DefWirLengthTypeNotFound_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Degree of maturity ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DegreeOfMaturity_Caption() As String
            Get
                Return ResourceManager.GetString("DegreeOfMaturity_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die [DELETED]  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Deleted_CellValue() As String
            Get
                Return ResourceManager.GetString("Deleted_CellValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Deleted ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Deleted() As String
            Get
                Return ResourceManager.GetString("Deleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0}Deleted -&gt; {1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Deleted_TooltipPart() As String
            Get
                Return ResourceManager.GetString("Deleted_TooltipPart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0}Deleted -&gt; {1} {2} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Deleted2_TooltipPart() As String
            Get
                Return ResourceManager.GetString("Deleted2_TooltipPart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0}Deleted -&gt; Type: {1} | Value: {2} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Deleted3_TooltipPart() As String
            Get
                Return ResourceManager.GetString("Deleted3_TooltipPart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Delete selected QM stamp(s)? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DeleteQMStamp_Msg() As String
            Get
                Return ResourceManager.GetString("DeleteQMStamp_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Delete selected redlining(s)? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DeleteRedlining_Msg() As String
            Get
                Return ResourceManager.GetString("DeleteRedlining_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Description_Caption() As String
            Get
                Return ResourceManager.GetString("Description_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die      Description:{0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Description_ExcelComment() As String
            Get
                Return ResourceManager.GetString("Description_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die      Designer department:{0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DesDep_ExcelComment() As String
            Get
                Return ResourceManager.GetString("DesDep_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Diff. type ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DiffType_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("DiffType_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die      Document number:{0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocNum_ExcelComment() As String
            Get
                Return ResourceManager.GetString("DocNum_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die      Document type:{0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocTyp_ExcelComment() As String
            Get
                Return ResourceManager.GetString("DocTyp_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Edit... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Edit_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("Edit_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Edit redlining... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property EditRedlining_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("EditRedlining_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Error_RedliningType() As String
            Get
                Return ResourceManager.GetString("Error_RedliningType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while exporting data to Excel!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorExportExcel_Msg() As String
            Get
                Return ResourceManager.GetString("ErrorExportExcel_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while filling data grids with KBL information of compare result!{0}{1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorFillCompGridData_Msg() As String
            Get
                Return ResourceManager.GetString("ErrorFillCompGridData_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while filling data grids with KBL information!{0}{1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorFillGridData_Msg() As String
            Get
                Return ResourceManager.GetString("ErrorFillGridData_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while filling mapper structure of loaded KBL data!{0}{1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorFillMapper_Msg() As String
            Get
                Return ResourceManager.GetString("ErrorFillMapper_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while getting running E3 application instances from binding context: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorGetE3App_LogMsg() As String
            Get
                Return ResourceManager.GetString("ErrorGetE3App_LogMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while initializing grid data sources for compare result!{0}{1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorInitCompGridData_Msg() As String
            Get
                Return ResourceManager.GetString("ErrorInitCompGridData_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while initializing grid data sources of loaded KBL model!{0}{1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorInitGridData_Msg() As String
            Get
                Return ResourceManager.GetString("ErrorInitGridData_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while trying to load graphical redlining. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorLoadGraphRedlining_Msg() As String
            Get
                Return ResourceManager.GetString("ErrorLoadGraphRedlining_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Expand all rows ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExpandAll_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("ExpandAll_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Export to Excel... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportExcel_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("ExportExcel_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Excel export successfully finished! Open created workbook? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportExcelFinished_Msg() As String
            Get
                Return ResourceManager.GetString("ExportExcelFinished_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Exporting data table &apos;{0}&apos; to Excel... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportingToExcel_LogMsg() As String
            Get
                Return ResourceManager.GetString("ExportingToExcel_LogMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Export only active/selected rows? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportSelRows_Msg() As String
            Get
                Return ResourceManager.GetString("ExportSelRows_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Export selected data table rows to Excel... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportSelRowsToExcelFile_Title() As String
            Get
                Return ResourceManager.GetString("ExportSelRowsToExcelFile_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Export {0} to Excel... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportTableToExcel_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("ExportTableToExcel_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Doc. type: {0} | Doc. number: {1} | Change level: {2} | File name: {3} | Location: {4} | Data format: {5} | Creating system: {6} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExtReference_TooltipPart() As String
            Get
                Return ResourceManager.GetString("ExtReference_TooltipPart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die External references ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExtReferences_Caption() As String
            Get
                Return ResourceManager.GetString("ExtReferences_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die      File name:{0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FileName_ExcelComment() As String
            Get
                Return ResourceManager.GetString("FileName_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Finished loading KBL document at {0}... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FinishedLoadKBL_LogMsg() As String
            Get
                Return ResourceManager.GetString("FinishedLoadKBL_LogMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0}Added -&gt; Id: {1} | Description: {2} | Part number: {3} | Location: {4} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FixingAssignmentAdd_TooltipPart() As String
            Get
                Return ResourceManager.GetString("FixingAssignmentAdd_TooltipPart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0}Deleted -&gt; Id: {1} | Description: {2} | Part number: {3} | Location: {4} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FixingAssignmentDel_TooltipPart() As String
            Get
                Return ResourceManager.GetString("FixingAssignmentDel_TooltipPart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fixing assignments ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FixingAssignments_Caption() As String
            Get
                Return ResourceManager.GetString("FixingAssignments_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die  flat ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FlatSuffix1_ExcelWorksheet() As String
            Get
                Return ResourceManager.GetString("FlatSuffix1_ExcelWorksheet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0} flat ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FlatSuffix2_ExcelWorksheet() As String
            Get
                Return ResourceManager.GetString("FlatSuffix2_ExcelWorksheet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Graphical ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Graphical_RedliningType() As String
            Get
                Return ResourceManager.GetString("Graphical_RedliningType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Group ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Group_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("Group_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Highlight entire routing path ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property HighlightRoutingPath_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("HighlightRoutingPath_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Id:{0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Id_ExcelComment() As String
            Get
                Return ResourceManager.GetString("Id_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Info_RedliningType() As String
            Get
                Return ResourceManager.GetString("Info_RedliningType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Installation information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InstallInfo_Caption() As String
            Get
                Return ResourceManager.GetString("InstallInfo_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die      Instruction type:{0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InstrType_ExcelComment() As String
            Get
                Return ResourceManager.GetString("InstrType_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Instruction type: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InstrType2_ExcelComment() As String
            Get
                Return ResourceManager.GetString("InstrType2_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die      Instruction value:{0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InstrVal_ExcelComment() As String
            Get
                Return ResourceManager.GetString("InstrVal_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die |Instruction value: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InstrVal2_ExcelComment() As String
            Get
                Return ResourceManager.GetString("InstrVal2_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Last changed by ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LastChangedBy_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("LastChangedBy_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Last changed on ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LastChangedOn_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("LastChangedOn_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Length information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Length_RedliningType() As String
            Get
                Return ResourceManager.GetString("Length_RedliningType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Length information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LengthInfo_Caption() As String
            Get
                Return ResourceManager.GetString("LengthInfo_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Length type: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LengthType_ExcelComment() As String
            Get
                Return ResourceManager.GetString("LengthType_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die |Length value: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LengthValue_ExcelComment() As String
            Get
                Return ResourceManager.GetString("LengthValue_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Linked modules of selected object ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LinkedModules_Caption() As String
            Get
                Return ResourceManager.GetString("LinkedModules_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die      Location:{0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Loc_ExcelComment() As String
            Get
                Return ResourceManager.GetString("Loc_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Localized Descriptions ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LocDescription_Caption() As String
            Get
                Return ResourceManager.GetString("LocDescription_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mark selected object(s) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MarkSelObjs_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("MarkSelObjs_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mass information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MassInfo_Caption() As String
            Get
                Return ResourceManager.GetString("MassInfo_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Material information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MatInfo_Caption() As String
            Get
                Return ResourceManager.GetString("MatInfo_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die      Material key:{0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MatKey_ExcelComment() As String
            Get
                Return ResourceManager.GetString("MatKey_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die      Material reference system:{0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MatRefSys_ExcelComment() As String
            Get
                Return ResourceManager.GetString("MatRefSys_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Model year ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ModelYear_Caption() As String
            Get
                Return ResourceManager.GetString("ModelYear_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die [MODIFIED]  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Modified_CellValue() As String
            Get
                Return ResourceManager.GetString("Modified_CellValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Modified ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Modified() As String
            Get
                Return ResourceManager.GetString("Modified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die [Cavity] {0},{1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MountingCav_ExcelComment() As String
            Get
                Return ResourceManager.GetString("MountingCav_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die [Connector] {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MountingConn_ExcelComment() As String
            Get
                Return ResourceManager.GetString("MountingConn_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mounted objects ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MountingObjects_Caption() As String
            Get
                Return ResourceManager.GetString("MountingObjects_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die [Slot] {0},{1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MountingSlot_ExcelComment() As String
            Get
                Return ResourceManager.GetString("MountingSlot_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No linked module information available! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NoLinkedModules_Msg() As String
            Get
                Return ResourceManager.GetString("NoLinkedModules_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No sheet found with selected wire in current opened E3 application! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NoSheetFound_LogMsg() As String
            Get
                Return ResourceManager.GetString("NoSheetFound_LogMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Object contains one or more validity check result(s)! Click cell button on right side for more information. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ObjectContainsOneOrMoreValidityCheckResults_TooltipText() As String
            Get
                Return ResourceManager.GetString("ObjectContainsOneOrMoreValidityCheckResults_TooltipText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ref. object name(s) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ObjectNames_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("ObjectNames_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ref. object type(s) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ObjectTypes_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("ObjectTypes_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Object name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ObjName_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("ObjName_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Object type ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ObjType_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("ObjType_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Part number ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PartNumber_Caption() As String
            Get
                Return ResourceManager.GetString("PartNumber_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Part number type ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PartNumberType_Caption() As String
            Get
                Return ResourceManager.GetString("PartNumberType_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Passed ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Passed_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("Passed_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die modified ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PlacementModified() As String
            Get
                Return ResourceManager.GetString("PlacementModified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Plug part ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PlugPart_Caption() As String
            Get
                Return ResourceManager.GetString("PlugPart_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Predecessor part number ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PredPartNumber_Caption() As String
            Get
                Return ResourceManager.GetString("PredPartNumber_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Project number ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PrjNumber_Caption() As String
            Get
                Return ResourceManager.GetString("PrjNumber_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Problem occurred while exporting data to Excel: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProblemExportExcel_LogMsg() As String
            Get
                Return ResourceManager.GetString("ProblemExportExcel_LogMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Problem occurred while filling data grids with KBL information: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProblemFillGridData_LogMsg() As String
            Get
                Return ResourceManager.GetString("ProblemFillGridData_LogMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Problem occurred while initializing grid data sources of loaded KBL model: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProblemInitGridData_LogMsg() As String
            Get
                Return ResourceManager.GetString("ProblemInitGridData_LogMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Problem occurred while loading object mapper from KBL data: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProblemLoadMapper_LogMsg() As String
            Get
                Return ResourceManager.GetString("ProblemLoadMapper_LogMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Processing information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProcInfo_Caption() As String
            Get
                Return ResourceManager.GetString("ProcInfo_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Property name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PropName_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("PropName_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Property value ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PropVal_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("PropVal_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Question_RedliningType() As String
            Get
                Return ResourceManager.GetString("Question_RedliningType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cannot edit redlinings for selected object because valid user ID is missing! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RedliningNotPossible_Msg() As String
            Get
                Return ResourceManager.GetString("RedliningNotPossible_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Referenced cavities ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RefCavs_Caption() As String
            Get
                Return ResourceManager.GetString("RefCavs_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Referenced components ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RefComps_Caption() As String
            Get
                Return ResourceManager.GetString("RefComps_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Reference document:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RefDoc_TooltipPart() As String
            Get
                Return ResourceManager.GetString("RefDoc_TooltipPart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Referenced elements ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RefElement_Caption() As String
            Get
                Return ResourceManager.GetString("RefElement_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die [REF.]  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Reference_CellValue() As String
            Get
                Return ResourceManager.GetString("Reference_CellValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ref. no. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RefNo_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("RefNo_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ref. no. already in use! Assign new number anyway? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RefNoAlreadyInUse_Msg() As String
            Get
                Return ResourceManager.GetString("RefNoAlreadyInUse_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ref. no. cannot be empty! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RefNoCannotBeEmpty_Msg() As String
            Get
                Return ResourceManager.GetString("RefNoCannotBeEmpty_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die      Responsible designer:{0}&quot; ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RespDes_ExcelComment() As String
            Get
                Return ResourceManager.GetString("RespDes_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Routing information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RoutingInfo_Caption() As String
            Get
                Return ResourceManager.GetString("RoutingInfo_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Row count: {0}      Filter row count: {1}      Visible row count: {2}      Selected row count: {3} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RowCount_Label() As String
            Get
                Return ResourceManager.GetString("RowCount_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die      Scope:{0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Scope_ExcelComment() As String
            Get
                Return ResourceManager.GetString("Scope_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Seal part ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SealPart_Caption() As String
            Get
                Return ResourceManager.GetString("SealPart_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Segment: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Seg_ExcelComment() As String
            Get
                Return ResourceManager.GetString("Seg_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please select at least one object first! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SelectObjectFirst_Msg() As String
            Get
                Return ResourceManager.GetString("SelectObjectFirst_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Select marked object(s) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SelMarkedObjs_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("SelMarkedObjs_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Calculating positions for splice ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShowBestProposal() As String
            Get
                Return ResourceManager.GetString("ShowBestProposal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Show bundle cross section... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShowBundleCS_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("ShowBundleCS_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Show connectivity... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShowConnectivity_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("ShowConnectivity_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Show contacting ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShowContacting_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("ShowContacting_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Show corresponding ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShowCorresponding_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("ShowCorresponding_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Show module(s)... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShowMods_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("ShowMods_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Show overall connectivity... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShowOverallConnectivity_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("ShowOverallConnectivity_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Show entire routing path... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShowRoutingPath_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("ShowRoutingPath_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Show rubberlines to corresponding connectors ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShowRubberlines() As String
            Get
                Return ResourceManager.GetString("ShowRubberlines", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Show schematics... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShowSchematics_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("ShowSchematics_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Show proposals for position ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShowSpliceProposals() As String
            Get
                Return ResourceManager.GetString("ShowSpliceProposals", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Show start/end connectors... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShowStartEndConns_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("ShowStartEndConns_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Specification ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Specification_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("Specification_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No alternative positions could be found for this splice. There may be no connectivity available. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SpliceLocator_Msg() As String
            Get
                Return ResourceManager.GetString("SpliceLocator_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Start loading KBL document at {0}... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartLoadKBL_LogMsg() As String
            Get
                Return ResourceManager.GetString("StartLoadKBL_LogMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Terminal part ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TerminalPart_Caption() As String
            Get
                Return ResourceManager.GetString("TerminalPart_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Terminal plating material different: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TermPlatingMatDiff_TooltipText() As String
            Get
                Return ResourceManager.GetString("TermPlatingMatDiff_TooltipText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die To be changed ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ToBeChanged_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("ToBeChanged_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Value determination: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ValDet_ExcelComment() As String
            Get
                Return ResourceManager.GetString("ValDet_ExcelComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Version_Caption() As String
            Get
                Return ResourceManager.GetString("Version_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Visible ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Visible_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("Visible_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Calculation of distance between selected objects not possible!{0}Multiple segment routing pathes found. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Warning1CalcDist_Msg() As String
            Get
                Return ResourceManager.GetString("Warning1CalcDist_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Calculation of distance between selected objects not possible!{0}Referenced start and/or end vertex could not be determined. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Warning2CalcDist_Msg() As String
            Get
                Return ResourceManager.GetString("Warning2CalcDist_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die One or more value(s) exceed the maximum allowed Excel cell limit and have been truncated! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WarningExcelCellLimit_Msg() As String
            Get
                Return ResourceManager.GetString("WarningExcelCellLimit_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Enumeration of running object table failed while getting running E3 application instances. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WarningGetE3App_LogMsg() As String
            Get
                Return ResourceManager.GetString("WarningGetE3App_LogMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Calculating... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WeightCalc_Calculating() As String
            Get
                Return ResourceManager.GetString("WeightCalc_Calculating", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wires/Cores ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WiresTab_Caption() As String
            Get
                Return ResourceManager.GetString("WiresTab_Caption", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to PrimaryLength_Caption.
        '''</summary>
        Friend Shared ReadOnly Property PrimaryLength_Caption() As String
            Get
                Return ResourceManager.GetString("PrimaryLength_Caption", resourceCulture)
            End Get
        End Property

    End Class
End Namespace
