'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class InlinerPairDetailsStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Zuken.E3.HarnessAnalyzer.InlinerPairDetailsStrings", GetType(InlinerPairDetailsStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die ERROR: Cavity count/numbering or wire count mismatch! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CavityWireCountMismatch_TooltipText() As String
            Get
                Return ResourceManager.GetString("CavityWireCountMismatch_TooltipText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cavity ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CavNum_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("CavNum_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Color ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Color_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("Color_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wire color mismatch! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ColorMismatch_TooltipText() As String
            Get
                Return ResourceManager.GetString("ColorMismatch_TooltipText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Con. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Connector_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("Connector_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die CSA ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CSA_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("CSA_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wire CSA mismatch! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CSAMismatch_TooltipText() As String
            Get
                Return ResourceManager.GetString("CSAMismatch_TooltipText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die ERROR:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Error_TooltipText() As String
            Get
                Return ResourceManager.GetString("Error_TooltipText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Left inliner housing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LeftInlHousing_GroupCaption() As String
            Get
                Return ResourceManager.GetString("LeftInlHousing_GroupCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Modules ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Modules_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("Modules_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Plating ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Plating_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("Plating_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Right inliner housing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RightInlHousing_GroupCaption() As String
            Get
                Return ResourceManager.GetString("RightInlHousing_GroupCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Signal ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Signal_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("Signal_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Signal mismatch! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SignalMismatch_TooltipText() As String
            Get
                Return ResourceManager.GetString("SignalMismatch_TooltipText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Terminal ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Terminal_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("Terminal_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Terminal plating mismatch! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TerminalPlatingMismatch_TooltipText() As String
            Get
                Return ResourceManager.GetString("TerminalPlatingMismatch_TooltipText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Type_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("Type_ColumnCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wire type mismatch! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TypeMismatch_TooltipText() As String
            Get
                Return ResourceManager.GetString("TypeMismatch_TooltipText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die WARNING:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Warning_TooltipText() As String
            Get
                Return ResourceManager.GetString("Warning_TooltipText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wire ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Wire_ColumnCaption() As String
            Get
                Return ResourceManager.GetString("Wire_ColumnCaption", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
