'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class LoggingStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Zuken.E3.HarnessAnalyzer.LoggingStrings", GetType(LoggingStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Import of memolist item &apos;{0}&apos; on {1} object &apos;{2}&apos; failed: KBL ID of referred object not exists in current document. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocStatMachine_ImportMemolistFailed() As String
            Get
                Return ResourceManager.GetString("DocStatMachine_ImportMemolistFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Import of QM stamp with ref. no. &apos;{0}&apos; failed: KBL ID of referred objects not exists in current document. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocStatMachine_ImportQMStampFailed() As String
            Get
                Return ResourceManager.GetString("DocStatMachine_ImportQMStampFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Import of redlining &apos;{0}&apos; on {1} object &apos;{2}&apos; failed: KBL ID of referred object not exists in current document. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocStatMachine_ImportRedliningFailed() As String
            Get
                Return ResourceManager.GetString("DocStatMachine_ImportRedliningFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Finished loading draft drawing at {0}... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DraftConv_FinishedLoadDrawing() As String
            Get
                Return ResourceManager.GetString("DraftConv_FinishedLoadDrawing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Loading draft drawing... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DraftConv_LoadingDrawing() As String
            Get
                Return ResourceManager.GetString("DraftConv_LoadingDrawing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No graphical segment or vertex information included in KBL file! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DraftConv_NoSegmentVertexInKBL() As String
            Get
                Return ResourceManager.GetString("DraftConv_NoSegmentVertexInKBL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Problem occurred while loading accessories for draft drawing: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DraftConv_ProblemLoadAccessories() As String
            Get
                Return ResourceManager.GetString("DraftConv_ProblemLoadAccessories", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Problem occurred while loading additional drawing for draft drawing: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DraftConv_ProblemLoadDrawing() As String
            Get
                Return ResourceManager.GetString("DraftConv_ProblemLoadDrawing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Problem occurred while loading fixings for draft drawing: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DraftConv_ProblemLoadFixings() As String
            Get
                Return ResourceManager.GetString("DraftConv_ProblemLoadFixings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Problem occurred while loading segments for draft drawing: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DraftConv_ProblemLoadSegments() As String
            Get
                Return ResourceManager.GetString("DraftConv_ProblemLoadSegments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Problem occurred while loading vertices for draft drawing: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DraftConv_ProblemLoadVertices() As String
            Get
                Return ResourceManager.GetString("DraftConv_ProblemLoadVertices", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Start loading draft drawing at {0}... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DraftConv_StartLoadDrawing() As String
            Get
                Return ResourceManager.GetString("DraftConv_StartLoadDrawing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Initialize licensing... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InitMng_InitLic() As String
            Get
                Return ResourceManager.GetString("InitMng_InitLic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cancelled loading of SVG file &apos;{0}&apos; at {1}... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SvgConv_CancelledLoadDrawing() As String
            Get
                Return ResourceManager.GetString("SvgConv_CancelledLoadDrawing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Finished loading SVG file &apos;{0}&apos; at {1}... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SvgConv_FinishedLoadDrawing() As String
            Get
                Return ResourceManager.GetString("SvgConv_FinishedLoadDrawing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Loading SVG drawing &apos;{0}&apos;... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SvgConv_LoadingDrawing() As String
            Get
                Return ResourceManager.GetString("SvgConv_LoadingDrawing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die SVG drawing could not be completely loaded! {0}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SvgConv_LoadProblem() As String
            Get
                Return ResourceManager.GetString("SvgConv_LoadProblem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Problem occurred while checking SVG file for consistency: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SvgConv_ProblemCheckSVG() As String
            Get
                Return ResourceManager.GetString("SvgConv_ProblemCheckSVG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Problem occurred in line &apos;{0}&apos; while loading SVG file &apos;{1}&apos;: {2} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SvgConv_ProblemLoadSVG() As String
            Get
                Return ResourceManager.GetString("SvgConv_ProblemLoadSVG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Start loading SVG file &apos;{0}&apos; at {1}... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SvgConv_StartLoadFile() As String
            Get
                Return ResourceManager.GetString("SvgConv_StartLoadFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Validation of SVG file &apos;{0}&apos; failed: There is an element &apos;{1}&apos; in line {2} which does not belong to a group (it will not be visible)! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SvgConv_ValidationFailsGroup() As String
            Get
                Return ResourceManager.GetString("SvgConv_ValidationFailsGroup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Validation of SVG file &apos;{0}&apos; yields warning: There is an element &apos;{1}&apos; in line {2} (&apos;{3}&apos;) which has white fill color and/or set transparent (it might not be visible)! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SvgConv_ValidationFailsText() As String
            Get
                Return ResourceManager.GetString("SvgConv_ValidationFailsText", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
