'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class MainFormStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Zuken.E3.HarnessAnalyzer.MainFormStrings", GetType(MainFormStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cannot find JT model file in specified location! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CannotFindJTModelFileInSpecifiedLocation() As String
            Get
                Return ResourceManager.GetString("CannotFindJTModelFileInSpecifiedLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Generation of schematics for a KSL-connector is not possible! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CantShowKSLConnectorSchematics_Msg() As String
            Get
                Return ResourceManager.GetString("CantShowKSLConnectorSchematics_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Click info button for more details! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ClickInfoForMoreDetails() As String
            Get
                Return ResourceManager.GetString("ClickInfoForMoreDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Visibility in 3D view ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property D3DVisibilityToolTipTabText() As String
            Get
                Return ResourceManager.GetString("D3DVisibilityToolTipTabText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Could not find HCV/XHCV file parameter: &quot;&quot;{0}&quot;&quot;! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorFindParameter_Msg() As String
            Get
                Return ResourceManager.GetString("ErrorFindParameter_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while loading configuration file with general application settings!{0}Use default values.{0}{1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorLoadAppSettings_Msg() As String
            Get
                Return ResourceManager.GetString("ErrorLoadAppSettings_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while loading configuration file with bundle diameter settings!{0}Use default values.{0}{1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorLoadDiaSettings_Msg() As String
            Get
                Return ResourceManager.GetString("ErrorLoadDiaSettings_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while loading configuration file with E3Xml settings!{0}Using default values.{0}{1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorLoadE3XmlSettings_Msg() As String
            Get
                Return ResourceManager.GetString("ErrorLoadE3XmlSettings_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while loading configuration file with QM stamp specifications!{0}Use default values.{0}{1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorLoadStampSpec_Msg() As String
            Get
                Return ResourceManager.GetString("ErrorLoadStampSpec_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while loading configuration file with weight calculation settings!{0}Using default values.{0}{1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorLoadWeightSettings_Msg() As String
            Get
                Return ResourceManager.GetString("ErrorLoadWeightSettings_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while opening selected file! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorOpenFile_Msg() As String
            Get
                Return ResourceManager.GetString("ErrorOpenFile_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Export drawing... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportDrw_StatMsg() As String
            Get
                Return ResourceManager.GetString("ExportDrw_StatMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Exporting all data table information to Excel... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportingToExcel_StatMsg() As String
            Get
                Return ResourceManager.GetString("ExportingToExcel_StatMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InfoButtonText() As String
            Get
                Return ResourceManager.GetString("InfoButtonText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Initialize SVG drawing... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InitSVGDraw_StatMsg() As String
            Get
                Return ResourceManager.GetString("InitSVGDraw_StatMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Loading schematics .... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LoadingSchematics_Msg() As String
            Get
                Return ResourceManager.GetString("LoadingSchematics_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die E³.HarnessAnalyzer application requires Microsoft .NET Framework 4.5!{0}Please download and install it from http://www.microsoft.com/en-us/download/details.aspx?id=30653. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MissingFramework_Msg() As String
            Get
                Return ResourceManager.GetString("MissingFramework_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Module changes ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ModuleChanges_GridTableDescription() As String
            Get
                Return ResourceManager.GetString("ModuleChanges_GridTableDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Net connections ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NetConns_GridTableDescription() As String
            Get
                Return ResourceManager.GetString("NetConns_GridTableDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die No further routing pathes found for selected cable/wire in other opened HCV documents! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NoRoutingPathFound_Msg() As String
            Get
                Return ResourceManager.GetString("NoRoutingPathFound_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Not a valid E³.HarnessAnalyzer file parameter: &quot;&quot;{0}&quot;&quot;! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NotValidParameter_Msg() As String
            Get
                Return ResourceManager.GetString("NotValidParameter_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Segment protections ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SegProts_GridTableDescription() As String
            Get
                Return ResourceManager.GetString("SegProts_GridTableDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Successfully exported Document to KBL &quot;{0}&quot; ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SuccessfullyExportedKBL() As String
            Get
                Return ResourceManager.GetString("SuccessfullyExportedKBL", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
