'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class MemolistHubStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Zuken.E3.HarnessAnalyzer.MemolistHubStrings", GetType(MemolistHubStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Check all items ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CheckAll_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("CheckAll_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Comment ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Comment_ColCaption() As String
            Get
                Return ResourceManager.GetString("Comment_ColCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Loading and initializing of memolist tree failed!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorLoadTree_Msg() As String
            Get
                Return ResourceManager.GetString("ErrorLoadTree_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Id ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Id_ColCaption() As String
            Get
                Return ResourceManager.GetString("Id_ColCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die IsSelected ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property IsSelected_ColCaption() As String
            Get
                Return ResourceManager.GetString("IsSelected_ColCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Name_ColCaption() As String
            Get
                Return ResourceManager.GetString("Name_ColCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Remove all items ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RemAll_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("RemAll_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Remove all items from memolist? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RemFromMemolist_Msg() As String
            Get
                Return ResourceManager.GetString("RemFromMemolist_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Remove selected item(s) ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RemSelItem_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("RemSelItem_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Type_ColCaption() As String
            Get
                Return ResourceManager.GetString("Type_ColCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Uncheck all items ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property UncheckAll_CtxtMnu_Caption() As String
            Get
                Return ResourceManager.GetString("UncheckAll_CtxtMnu_Caption", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
