'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ObjectPropertyNameStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Zuken.E3.HarnessAnalyzer.ObjectPropertyNameStrings", GetType(ObjectPropertyNameStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Abbreviation ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Abbreviation() As String
            Get
                Return ResourceManager.GetString("Abbreviation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Accessory type ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AccessoryType() As String
            Get
                Return ResourceManager.GetString("AccessoryType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Add. extremities ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AddExtremities() As String
            Get
                Return ResourceManager.GetString("AddExtremities", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Add. extremities ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AdditionalExtrimities() As String
            Get
                Return ResourceManager.GetString("AdditionalExtrimities", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Alias id ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AliasId() As String
            Get
                Return ResourceManager.GetString("AliasId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Approver department ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ApproverDepartment() As String
            Get
                Return ResourceManager.GetString("ApproverDepartment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Approver name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ApproverName() As String
            Get
                Return ResourceManager.GetString("ApproverName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Bend radius ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BendRadius() As String
            Get
                Return ResourceManager.GetString("BendRadius", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cable designator ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CableDesignator() As String
            Get
                Return ResourceManager.GetString("CableDesignator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cable number ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CableNumber() As String
            Get
                Return ResourceManager.GetString("CableNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Car classification level 2 ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CarClassLevel2() As String
            Get
                Return ResourceManager.GetString("CarClassLevel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Car classification level 3 ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CarClassLevel3() As String
            Get
                Return ResourceManager.GetString("CarClassLevel3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Car classification level 4 ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CarClassLevel4() As String
            Get
                Return ResourceManager.GetString("CarClassLevel4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cavity count ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CavityCount() As String
            Get
                Return ResourceManager.GetString("CavityCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cavity number ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CavityNumber() As String
            Get
                Return ResourceManager.GetString("CavityNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Change ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Change() As String
            Get
                Return ResourceManager.GetString("Change", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Change date ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ChangeDate() As String
            Get
                Return ResourceManager.GetString("ChangeDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Changed elements ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ChangedElements() As String
            Get
                Return ResourceManager.GetString("ChangedElements", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Change request ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ChangeRequest() As String
            Get
                Return ResourceManager.GetString("ChangeRequest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Color ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Color() As String
            Get
                Return ResourceManager.GetString("Color", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Company name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CompanyName() As String
            Get
                Return ResourceManager.GetString("CompanyName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Component pin maps ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ComponentPinMaps() As String
            Get
                Return ResourceManager.GetString("ComponentPinMaps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Content ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Content() As String
            Get
                Return ResourceManager.GetString("Content", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Copyright note ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CopyrightNote() As String
            Get
                Return ResourceManager.GetString("CopyrightNote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Core color ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CoreColor() As String
            Get
                Return ResourceManager.GetString("CoreColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Core id ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CoreId() As String
            Get
                Return ResourceManager.GetString("CoreId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Core number ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CoreNumber() As String
            Get
                Return ResourceManager.GetString("CoreNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Core type ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CoreType() As String
            Get
                Return ResourceManager.GetString("CoreType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cover color ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CoverColor() As String
            Get
                Return ResourceManager.GetString("CoverColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cross section area ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CrossSectionArea() As String
            Get
                Return ResourceManager.GetString("CrossSectionArea", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DateOfApproval() As String
            Get
                Return ResourceManager.GetString("DateOfApproval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Degree of maturity ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DegreeOfMaturity() As String
            Get
                Return ResourceManager.GetString("DegreeOfMaturity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Department ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Department() As String
            Get
                Return ResourceManager.GetString("Department", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Description() As String
            Get
                Return ResourceManager.GetString("Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Designer department ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DesignerDepartment() As String
            Get
                Return ResourceManager.GetString("DesignerDepartment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dim. value ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DimValue() As String
            Get
                Return ResourceManager.GetString("DimValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dim. value range ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DimValueRange() As String
            Get
                Return ResourceManager.GetString("DimValueRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die End cavity ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property EndCavity() As String
            Get
                Return ResourceManager.GetString("EndCavity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die End connector ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property EndConnector() As String
            Get
                Return ResourceManager.GetString("EndConnector", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die End location ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property EndLocation() As String
            Get
                Return ResourceManager.GetString("EndLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die End location abs. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property EndLocationAbsolute() As String
            Get
                Return ResourceManager.GetString("EndLocationAbsolute", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die End vertex ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property EndVertex() As String
            Get
                Return ResourceManager.GetString("EndVertex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die External references ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExternalReferences() As String
            Get
                Return ResourceManager.GetString("ExternalReferences", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fixing assignment ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FixingAssignment() As String
            Get
                Return ResourceManager.GetString("FixingAssignment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Fixing type ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FixingType() As String
            Get
                Return ResourceManager.GetString("FixingType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Folding direction ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property FoldingDirection() As String
            Get
                Return ResourceManager.GetString("FoldingDirection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Form ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Form() As String
            Get
                Return ResourceManager.GetString("Form", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Module ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property HarnessModule() As String
            Get
                Return ResourceManager.GetString("HarnessModule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Housing code ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property HousingCode() As String
            Get
                Return ResourceManager.GetString("HousingCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Housing color ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property HousingColor() As String
            Get
                Return ResourceManager.GetString("HousingColor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Housing type ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property HousingType() As String
            Get
                Return ResourceManager.GetString("HousingType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Id ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Id() As String
            Get
                Return ResourceManager.GetString("Id", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Installation information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InstallationInformation() As String
            Get
                Return ResourceManager.GetString("InstallationInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Applied to ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property IsAppliedTo() As String
            Get
                Return ResourceManager.GetString("IsAppliedTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Is on top of ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property IsOnTopOf() As String
            Get
                Return ResourceManager.GetString("IsOnTopOf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die KEM ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property KEM() As String
            Get
                Return ResourceManager.GetString("KEM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Length information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LengthInformation() As String
            Get
                Return ResourceManager.GetString("LengthInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Localized descriptions ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LocalizedOccDescriptions() As String
            Get
                Return ResourceManager.GetString("LocalizedOccDescriptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Localized part descriptions ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LocalizedPartDescriptions() As String
            Get
                Return ResourceManager.GetString("LocalizedPartDescriptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Location abs. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LocationAbsolute() As String
            Get
                Return ResourceManager.GetString("LocationAbsolute", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Logistic control information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LogisticControlInfo() As String
            Get
                Return ResourceManager.GetString("LogisticControlInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Lower limit ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LowerLimit() As String
            Get
                Return ResourceManager.GetString("LowerLimit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mass information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MassInformation() As String
            Get
                Return ResourceManager.GetString("MassInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Material information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MaterialInformation() As String
            Get
                Return ResourceManager.GetString("MaterialInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Module configuration type ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ModConfigType() As String
            Get
                Return ResourceManager.GetString("ModConfigType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Model year ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ModelYear() As String
            Get
                Return ResourceManager.GetString("ModelYear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Mounted objects ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MountingObjects() As String
            Get
                Return ResourceManager.GetString("MountingObjects", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Name() As String
            Get
                Return ResourceManager.GetString("Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Net name ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NetName() As String
            Get
                Return ResourceManager.GetString("NetName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Nominal voltage ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NominalVoltage() As String
            Get
                Return ResourceManager.GetString("NominalVoltage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Origin ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Origin() As String
            Get
                Return ResourceManager.GetString("Origin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Outside diameter ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property OutsideDiameter() As String
            Get
                Return ResourceManager.GetString("OutsideDiameter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Part alias id ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PartAliasId() As String
            Get
                Return ResourceManager.GetString("PartAliasId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Part description ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PartDescription() As String
            Get
                Return ResourceManager.GetString("PartDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Part number ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PartNumber() As String
            Get
                Return ResourceManager.GetString("PartNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Part number type ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PartNumberType() As String
            Get
                Return ResourceManager.GetString("PartNumberType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Part processing information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PartProcessingInformation() As String
            Get
                Return ResourceManager.GetString("PartProcessingInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Part type ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PartType() As String
            Get
                Return ResourceManager.GetString("PartType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die per meter ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PerMeter() As String
            Get
                Return ResourceManager.GetString("PerMeter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Physical length ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PhysicalLength() As String
            Get
                Return ResourceManager.GetString("PhysicalLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Plating material ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Plating() As String
            Get
                Return ResourceManager.GetString("Plating", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Plug information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PlugInformation() As String
            Get
                Return ResourceManager.GetString("PlugInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Plug part number ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PlugPartNumber() As String
            Get
                Return ResourceManager.GetString("PlugPartNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Predecessor part number ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PredecessorPartNumber() As String
            Get
                Return ResourceManager.GetString("PredecessorPartNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Processing information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProcessingInformation() As String
            Get
                Return ResourceManager.GetString("ProcessingInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Processing info asgmt ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProcessingInformationAssignment() As String
            Get
                Return ResourceManager.GetString("ProcessingInformationAssignment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Project number ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProjectNumber() As String
            Get
                Return ResourceManager.GetString("ProjectNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Protection length ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProtectionLength() As String
            Get
                Return ResourceManager.GetString("ProtectionLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Protection type ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProtectionType() As String
            Get
                Return ResourceManager.GetString("ProtectionType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Referenced cavities ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReferencedCavities() As String
            Get
                Return ResourceManager.GetString("ReferencedCavities", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Referenced components ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReferencedComponents() As String
            Get
                Return ResourceManager.GetString("ReferencedComponents", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Reference element ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReferenceElement() As String
            Get
                Return ResourceManager.GetString("ReferenceElement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Related changes ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property RelatedChanges() As String
            Get
                Return ResourceManager.GetString("RelatedChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Responsible designer ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ResponsibleDesigner() As String
            Get
                Return ResourceManager.GetString("ResponsibleDesigner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Routing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Routing() As String
            Get
                Return ResourceManager.GetString("Routing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Seal information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SealInformation() As String
            Get
                Return ResourceManager.GetString("SealInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Seal part number ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SealPartNumber() As String
            Get
                Return ResourceManager.GetString("SealPartNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Segment location ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SegmentLocation() As String
            Get
                Return ResourceManager.GetString("SegmentLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SignalType() As String
            Get
                Return ResourceManager.GetString("SignalType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Start cavity ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartCavity() As String
            Get
                Return ResourceManager.GetString("StartCavity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Start connector ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartConnector() As String
            Get
                Return ResourceManager.GetString("StartConnector", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Start location ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartLocation() As String
            Get
                Return ResourceManager.GetString("StartLocation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Start location abs. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartLocationAbsolute() As String
            Get
                Return ResourceManager.GetString("StartLocationAbsolute", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Start vertex ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartVertex() As String
            Get
                Return ResourceManager.GetString("StartVertex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Taping direction ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TapingDirection() As String
            Get
                Return ResourceManager.GetString("TapingDirection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Target ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Target() As String
            Get
                Return ResourceManager.GetString("Target", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Terminal information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TerminalInformation() As String
            Get
                Return ResourceManager.GetString("TerminalInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Terminal part number ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TerminalPartNumber() As String
            Get
                Return ResourceManager.GetString("TerminalPartNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tolerance indication ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ToleranceIndication() As String
            Get
                Return ResourceManager.GetString("ToleranceIndication", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tolerance type ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ToleranceType() As String
            Get
                Return ResourceManager.GetString("ToleranceType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Type dependent parameter ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TypeDependentParameter() As String
            Get
                Return ResourceManager.GetString("TypeDependentParameter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TypeOfApproval() As String
            Get
                Return ResourceManager.GetString("TypeOfApproval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Upper limit ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property UpperLimit() As String
            Get
                Return ResourceManager.GetString("UpperLimit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Usage ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Usage() As String
            Get
                Return ResourceManager.GetString("Usage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Version() As String
            Get
                Return ResourceManager.GetString("Version", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Virtual length ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property VirtualLength() As String
            Get
                Return ResourceManager.GetString("VirtualLength", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Winding firmness ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WindingFirmness() As String
            Get
                Return ResourceManager.GetString("WindingFirmness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Winding type ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WindingType() As String
            Get
                Return ResourceManager.GetString("WindingType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wire/Core number ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WireCoreNumber() As String
            Get
                Return ResourceManager.GetString("WireCoreNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wire number ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WireNumber() As String
            Get
                Return ResourceManager.GetString("WireNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wire type ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WireType() As String
            Get
                Return ResourceManager.GetString("WireType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die ZGS ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ZGS() As String
            Get
                Return ResourceManager.GetString("ZGS", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
