'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class SchematicsViewStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Zuken.E3.HarnessAnalyzer.SchematicsViewStrings", GetType(SchematicsViewStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Assigned modules:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property AssignedModules_Tooltip() As String
            Get
                Return ResourceManager.GetString("AssignedModules_Tooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Color 1:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Color1_Tooltip() As String
            Get
                Return ResourceManager.GetString("Color1_Tooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Color 2:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Color2_Tooltip() As String
            Get
                Return ResourceManager.GetString("Color2_Tooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Kbl-schematics converter ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Converter_Log_Caption() As String
            Get
                Return ResourceManager.GetString("Converter_Log_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die CSA:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CSA_Tooltip() As String
            Get
                Return ResourceManager.GetString("CSA_Tooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while exporting connectivity view to the selected graphic file!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportError_Msg() As String
            Get
                Return ResourceManager.GetString("ExportError_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Problem occurred while exporting connectivity view! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportProblem_Msg() As String
            Get
                Return ResourceManager.GetString("ExportProblem_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Connectivity view successfully exported! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportSuccess_Msg() As String
            Get
                Return ResourceManager.GetString("ExportSuccess_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Export connectivity view as... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportViewToFile_Title() As String
            Get
                Return ResourceManager.GetString("ExportViewToFile_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wire information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WireCaption_Tooltip() As String
            Get
                Return ResourceManager.GetString("WireCaption_Tooltip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wire name:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WireName_Tooltip() As String
            Get
                Return ResourceManager.GetString("WireName_Tooltip", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
