'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class TopologyCompareTexts
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Zuken.E3.HarnessAnalyzer.TopologyCompareTexts", GetType(TopologyCompareTexts).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Compare was cancelled! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CompareCancelledMessage() As String
            Get
                Return ResourceManager.GetString("CompareCancelledMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Compare failed: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CompareFailedMessage() As String
            Get
                Return ResourceManager.GetString("CompareFailedMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Conversion cancelled! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ConversionCancelledMessage() As String
            Get
                Return ResourceManager.GetString("ConversionCancelledMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Conversion failed: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ConversionFailedMessage() As String
            Get
                Return ResourceManager.GetString("ConversionFailedMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0}. Direction ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DirectionVerticesWizardTabText() As String
            Get
                Return ResourceManager.GetString("DirectionVerticesWizardTabText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0}. Documents ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DocumentsWizardTabText() As String
            Get
                Return ResourceManager.GetString("DocumentsWizardTabText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Export was cancelled! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportCancelledMessage() As String
            Get
                Return ResourceManager.GetString("ExportCancelledMessage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Export finished successfully, open file now? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportFinishedSuccessfullyOpenQuestion() As String
            Get
                Return ResourceManager.GetString("ExportFinishedSuccessfullyOpenQuestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die no other document available! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property NoOtherDocumentAvailablePlaceHolderText() As String
            Get
                Return ResourceManager.GetString("NoOtherDocumentAvailablePlaceHolderText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0}. Compare ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartCompareWizardTabText() As String
            Get
                Return ResourceManager.GetString("StartCompareWizardTabText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Do you really want to close current compare and start with a new compare? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartNewCompareQuestion() As String
            Get
                Return ResourceManager.GetString("StartNewCompareQuestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0}. Start vertex pairs ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartVerticesWizardTabText() As String
            Get
                Return ResourceManager.GetString("StartVerticesWizardTabText", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
