'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class TopologyEditorFormStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Zuken.E3.HarnessAnalyzer.TopologyEditorFormStrings", GetType(TopologyEditorFormStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Background picture... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BackPic_MnuBtn_Caption() As String
            Get
                Return ResourceManager.GetString("BackPic_MnuBtn_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die New view file - Car topology editor ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Caption() As String
            Get
                Return ResourceManager.GetString("Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die [{0}] - Car topology editor ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Caption2() As String
            Get
                Return ResourceManager.GetString("Caption2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die   Define end corner of compartment in drawing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefEPOfComp_Label() As String
            Get
                Return ResourceManager.GetString("DefEPOfComp_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die   Define next point of polygon compartment in drawing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefNxtPOfComp_Label() As String
            Get
                Return ResourceManager.GetString("DefNxtPOfComp_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die   Define start corner of rectangle compartment in drawing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefSCOfComp_Label() As String
            Get
                Return ResourceManager.GetString("DefSCOfComp_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die   Define start point of polygon compartment in drawing ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DefSPOfComp_Label() As String
            Get
                Return ResourceManager.GetString("DefSPOfComp_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while exporting car topology to the selected graphic file!{0}{1}. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorExportTopo_Msg() As String
            Get
                Return ResourceManager.GetString("ErrorExportTopo_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while opening car topology view file! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorLoadTopo_Msg() As String
            Get
                Return ResourceManager.GetString("ErrorLoadTopo_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while saving car topology view file! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorSaveTopo_Msg() As String
            Get
                Return ResourceManager.GetString("ErrorSaveTopo_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Export... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Export_MnuBtn_Caption() As String
            Get
                Return ResourceManager.GetString("Export_MnuBtn_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Car topology successfully exported! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportTopoSuccess_Msg() As String
            Get
                Return ResourceManager.GetString("ExportTopoSuccess_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Export car topology view as... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportTopoToFile_Title() As String
            Get
                Return ResourceManager.GetString("ExportTopoToFile_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Load background picture... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LoadBackPicFile_Title() As String
            Get
                Return ResourceManager.GetString("LoadBackPicFile_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Open... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Open_MnuBtn_Caption() As String
            Get
                Return ResourceManager.GetString("Open_MnuBtn_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Open a valid car topology view file... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property OpenTopoFile_Title() As String
            Get
                Return ResourceManager.GetString("OpenTopoFile_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Place polygon compartment ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PlacePolyComp_MnuBtn_Caption() As String
            Get
                Return ResourceManager.GetString("PlacePolyComp_MnuBtn_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Place rectangle compartment ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PlaceRectComp_MnuBtn_Caption() As String
            Get
                Return ResourceManager.GetString("PlaceRectComp_MnuBtn_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Print... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Print_MnuBtn_Caption() As String
            Get
                Return ResourceManager.GetString("Print_MnuBtn_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Problem occurred while exporting car topology! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ProblemExportTopo_Msg() As String
            Get
                Return ResourceManager.GetString("ProblemExportTopo_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Save_MnuBtn_Caption() As String
            Get
                Return ResourceManager.GetString("Save_MnuBtn_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Save as... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SaveAs_MnuBtn_Caption() As String
            Get
                Return ResourceManager.GetString("SaveAs_MnuBtn_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Save changes? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SaveChanges_Msg() As String
            Get
                Return ResourceManager.GetString("SaveChanges_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Save current car topology view file as... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SaveTopoFile_Title() As String
            Get
                Return ResourceManager.GetString("SaveTopoFile_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Show grid ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ShowGrid_MnuBtn_Caption() As String
            Get
                Return ResourceManager.GetString("ShowGrid_MnuBtn_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Snap to grid ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property SnapGrid_MnuBtn_Caption() As String
            Get
                Return ResourceManager.GetString("SnapGrid_MnuBtn_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zoom extends ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ZoomExt_MnuBtn_Caption() As String
            Get
                Return ResourceManager.GetString("ZoomExt_MnuBtn_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zoom window ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ZoomWndw_MnuBtn_Caption() As String
            Get
                Return ResourceManager.GetString("ZoomWndw_MnuBtn_Caption", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
