'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class VoltageDropUserControlStrings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Zuken.E3.HarnessAnalyzer.VoltageDropUserControlStrings", GetType(VoltageDropUserControlStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CancelBtnText() As String
            Get
                Return ResourceManager.GetString("CancelBtnText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Conductor weight  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ConductorWeight() As String
            Get
                Return ResourceManager.GetString("ConductorWeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wire CSA  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CSA() As String
            Get
                Return ResourceManager.GetString("CSA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0} mm² ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CsaUnit() As String
            Get
                Return ResourceManager.GetString("CsaUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Voltage drop: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DeltaU() As String
            Get
                Return ResourceManager.GetString("DeltaU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0} V ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DeltaUUnit() As String
            Get
                Return ResourceManager.GetString("DeltaUUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die End terminal ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property EndCPTerminalDescription() As String
            Get
                Return ResourceManager.GetString("EndCPTerminalDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die End Resistance ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property EndResistance() As String
            Get
                Return ResourceManager.GetString("EndResistance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error while initializing voltage drop calculator: Given wire length or CSA value exceeds allowed minimum or maximum values! {0} Hint: {1} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ErrorInitCalculator_Msg() As String
            Get
                Return ResourceManager.GetString("ErrorInitCalculator_Msg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportSuccess() As String
            Get
                Return ResourceManager.GetString("ExportSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Export voltage drop for wire {0} to excel... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ExportTitel() As String
            Get
                Return ResourceManager.GetString("ExportTitel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Current: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InputCurrent() As String
            Get
                Return ResourceManager.GetString("InputCurrent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wire Length ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Length() As String
            Get
                Return ResourceManager.GetString("Length", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0} mm ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LengthUnit() As String
            Get
                Return ResourceManager.GetString("LengthUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Material ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Material() As String
            Get
                Return ResourceManager.GetString("Material", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Material density ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MaterialDensity() As String
            Get
                Return ResourceManager.GetString("MaterialDensity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0} g/cm³ ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property MaterialDensityUnit() As String
            Get
                Return ResourceManager.GetString("MaterialDensityUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Exported successfully. Do you want to open it? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property OpenExporteExcel_Dlg() As String
            Get
                Return ResourceManager.GetString("OpenExporteExcel_Dlg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Output ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Output() As String
            Get
                Return ResourceManager.GetString("Output", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Power dissipation:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PowerDissipation() As String
            Get
                Return ResourceManager.GetString("PowerDissipation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0} W ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property PowerUnit() As String
            Get
                Return ResourceManager.GetString("PowerUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die R  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property R() As String
            Get
                Return ResourceManager.GetString("R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0} Ω ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ResistanceUnit() As String
            Get
                Return ResourceManager.GetString("ResistanceUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Resistivity ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ResistivityCustom() As String
            Get
                Return ResourceManager.GetString("ResistivityCustom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0} x10⁻⁸ Ωm ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ResistivityUnit() As String
            Get
                Return ResourceManager.GetString("ResistivityUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Resistance:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Rges() As String
            Get
                Return ResourceManager.GetString("Rges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Start terminal  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartCPTerminalDescription() As String
            Get
                Return ResourceManager.GetString("StartCPTerminalDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Start Resistance  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property StartResistance() As String
            Get
                Return ResourceManager.GetString("StartResistance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Temperature ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property Temperature() As String
            Get
                Return ResourceManager.GetString("Temperature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0} °c ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TemperatureUnit() As String
            Get
                Return ResourceManager.GetString("TemperatureUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Conductor weight: ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TotalCondutorWeight() As String
            Get
                Return ResourceManager.GetString("TotalCondutorWeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Total weight ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TotalWeight() As String
            Get
                Return ResourceManager.GetString("TotalWeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Total weight:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TotalWeightLblText() As String
            Get
                Return ResourceManager.GetString("TotalWeightLblText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Type of wire ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property TypeOfWire() As String
            Get
                Return ResourceManager.GetString("TypeOfWire", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Voltage drop ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property VoltageDrop() As String
            Get
                Return ResourceManager.GetString("VoltageDrop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Voltage drop for wire {0}... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property VoltageDropTitel() As String
            Get
                Return ResourceManager.GetString("VoltageDropTitel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {0} g ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WeightUnit() As String
            Get
                Return ResourceManager.GetString("WeightUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wire or core number ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WireOrCorenumber() As String
            Get
                Return ResourceManager.GetString("WireOrCorenumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Wire resistance ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property WireResistance() As String
            Get
                Return ResourceManager.GetString("WireResistance", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
