'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Zuken.E3.HarnessAnalyzer.BorrowUtility.Strings", GetType(Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die ...Licenses borrowed successfully... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BorrowedSuccessfully_StatusText() As String
            Get
                Return ResourceManager.GetString("BorrowedSuccessfully_StatusText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die ...Licenses borrowed successfully with warnings... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BorrowedSuccessfullyWithWarnings_StatusText() As String
            Get
                Return ResourceManager.GetString("BorrowedSuccessfullyWithWarnings_StatusText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Borrowing licenses failed! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property BorrowingFailed_StatusText() As String
            Get
                Return ResourceManager.GetString("BorrowingFailed_StatusText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Please close E³.HarnessAnalyzer before borrowing a license! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property CloseHarnessAnalyzerBeforeBorrowing() As String
            Get
                Return ResourceManager.GetString("CloseHarnessAnalyzerBeforeBorrowing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Date must not be in the past! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property DateMustNotInPast_ValidationText() As String
            Get
                Return ResourceManager.GetString("DateMustNotInPast_ValidationText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Invalid Date ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property InvalidDate() As String
            Get
                Return ResourceManager.GetString("InvalidDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Warning, license path must be set or borrowing/licensing will not work as expected! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LicensePathMustBeSetOrWillNotWorkAsExpected_Message() As String
            Get
                Return ResourceManager.GetString("LicensePathMustBeSetOrWillNotWorkAsExpected_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die License path is not valid! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property LicensePathNotValid_Message() As String
            Get
                Return ResourceManager.GetString("LicensePathNotValid_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error, reset failed: {0} ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ResetFailed_Message() As String
            Get
                Return ResourceManager.GetString("ResetFailed_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Reset finished ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ResetFinished_Message() As String
            Get
                Return ResourceManager.GetString("ResetFinished_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die ...Licenses successfully returned... ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReturnedSuccessfully_StatusText() As String
            Get
                Return ResourceManager.GetString("ReturnedSuccessfully_StatusText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Returning licenses failed! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property ReturningFailed_StatusText() As String
            Get
                Return ResourceManager.GetString("ReturningFailed_StatusText", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
