' HINT: source: https://docs.microsoft.com/en-us/dotnet/api/system.printing.pagemediasizename?view=netframework-4.7.2
Imports System.Printing

Namespace Printing

    Public Class MediaSizeNameConverter

        Public Shared Function GetCleanName(pMediaSize As PageMediaSizeName) As String
            Select Case pMediaSize
                Case PageMediaSizeName.BusinessCard : Return "Business card"
                Case PageMediaSizeName.CreditCard : Return "Credit card"
                Case PageMediaSizeName.ISOA0 : Return "A0"
                Case PageMediaSizeName.ISOA1 : Return "A1"
                Case PageMediaSizeName.ISOA10 : Return "A10"
                Case PageMediaSizeName.ISOA2 : Return "A2"
                Case PageMediaSizeName.ISOA3 : Return "A3"
                Case PageMediaSizeName.ISOA3Extra : Return "A3 Extra"
                Case PageMediaSizeName.ISOA3Rotated : Return "A3 Rotated"
                Case PageMediaSizeName.ISOA4 : Return "A4"
                Case PageMediaSizeName.ISOA4Extra : Return "A4 Extra"
                Case PageMediaSizeName.ISOA4Rotated : Return "A4 Rotated"
                Case PageMediaSizeName.ISOA5 : Return "A5"
                Case PageMediaSizeName.ISOA5Extra : Return "A5 Extra"
                Case PageMediaSizeName.ISOA5Rotated : Return "A5 Rotated"
                Case PageMediaSizeName.ISOA6 : Return "A6"
                Case PageMediaSizeName.ISOA6Rotated : Return "A6 Rotated"
                Case PageMediaSizeName.ISOA7 : Return "A7"
                Case PageMediaSizeName.ISOA8 : Return "A8"
                Case PageMediaSizeName.ISOA9 : Return "A9"
                Case PageMediaSizeName.ISOB0 : Return "B0"
                Case PageMediaSizeName.ISOB1 : Return "B1"
                Case PageMediaSizeName.ISOB10 : Return "B10"
                Case PageMediaSizeName.ISOB2 : Return "B2"
                Case PageMediaSizeName.ISOB3 : Return "B3"
                Case PageMediaSizeName.ISOB4 : Return "B4"
                Case PageMediaSizeName.ISOB4Envelope : Return "B4 Envelope"
                Case PageMediaSizeName.ISOB5Envelope : Return "B5 Envelope"
                Case PageMediaSizeName.ISOB5Extra : Return "B5 Extra"
                Case PageMediaSizeName.ISOB7 : Return "B7"
                Case PageMediaSizeName.ISOB8 : Return "B8"
                Case PageMediaSizeName.ISOB9 : Return "B9"
                Case PageMediaSizeName.ISOC0 : Return "C0"
                Case PageMediaSizeName.ISOC1 : Return "C1"
                Case PageMediaSizeName.ISOC10 : Return "C10"
                Case PageMediaSizeName.ISOC2 : Return "C2"
                Case PageMediaSizeName.ISOC3 : Return "C3"
                Case PageMediaSizeName.ISOC3Envelope : Return "C3 Envelope"
                Case PageMediaSizeName.ISOC4 : Return "C4"
                Case PageMediaSizeName.ISOC4Envelope : Return "C4 Envelope"
                Case PageMediaSizeName.ISOC5 : Return "C5"
                Case PageMediaSizeName.ISOC5Envelope : Return "C5 Envelope"
                Case PageMediaSizeName.ISOC6 : Return "C6"
                Case PageMediaSizeName.ISOC6C5Envelope : Return "C6C5 Envelope"
                Case PageMediaSizeName.ISOC6Envelope : Return "C6 Envelope"
                Case PageMediaSizeName.ISOC7 : Return "C7"
                Case PageMediaSizeName.ISOC8 : Return "C8"
                Case PageMediaSizeName.ISOC9 : Return "C9"
                Case PageMediaSizeName.ISODLEnvelope : Return "DL Envelope"
                Case PageMediaSizeName.ISODLEnvelopeRotated : Return "DL Envelope Rotated"
                Case PageMediaSizeName.ISOSRA3 : Return "SRA 3"
                Case PageMediaSizeName.Japan2LPhoto : Return "2L Photo"
                Case PageMediaSizeName.JapanChou3Envelope : Return "Chou 3 Envelope"
                Case PageMediaSizeName.JapanChou3EnvelopeRotated : Return "Chou 3 Envelope Rotated"
                Case PageMediaSizeName.JapanChou4Envelope : Return "Chou 4 Envelope"
                Case PageMediaSizeName.JapanChou4EnvelopeRotated : Return "Chou 4 Envelope Rotated"
                Case PageMediaSizeName.JapanDoubleHagakiPostcard : Return "Double Hagaki Postcard"
                Case PageMediaSizeName.JapanDoubleHagakiPostcardRotated : Return "Double Hagaki Postcard Rotated"
                Case PageMediaSizeName.JapanHagakiPostcard : Return "Hagaki Postcard"
                Case PageMediaSizeName.JapanHagakiPostcardRotated : Return "Hagaki Postcard Rotated"
                Case PageMediaSizeName.JapanKaku2Envelope : Return "Kaku 2 Envelope"
                Case PageMediaSizeName.JapanKaku2EnvelopeRotated : Return "Kaku 2 Envelope Rotated"
                Case PageMediaSizeName.JapanKaku3Envelope : Return "Kaku 3 Envelope"
                Case PageMediaSizeName.JapanKaku3EnvelopeRotated : Return "Kaku 3 Envelope Rotated"
                Case PageMediaSizeName.JapanLPhoto : Return "L Photo"
                Case PageMediaSizeName.JapanQuadrupleHagakiPostcard : Return "Quadruple Hagaki Postcard"
                Case PageMediaSizeName.JapanYou1Envelope : Return "You 1 Envelope"
                Case PageMediaSizeName.JapanYou2Envelope : Return "You 2 Envelope"
                Case PageMediaSizeName.JapanYou3Envelope : Return "You 3 Envelope"
                Case PageMediaSizeName.JapanYou4Envelope : Return "You 4 Envelope"
                Case PageMediaSizeName.JapanYou4EnvelopeRotated : Return "You 4 Envelope Rotated"
                Case PageMediaSizeName.JapanYou6Envelope : Return "You 6 Envelope"
                Case PageMediaSizeName.JapanYou6EnvelopeRotated : Return "You 6 Envelope Rotated"
                Case PageMediaSizeName.JISB0 : Return "Japanese Industrial Standard B0"
                Case PageMediaSizeName.JISB1 : Return "Japanese Industrial Standard B1"
                Case PageMediaSizeName.JISB10 : Return "Japanese Industrial Standard B10"
                Case PageMediaSizeName.JISB2 : Return "Japanese Industrial Standard B2"
                Case PageMediaSizeName.JISB3 : Return "Japanese Industrial Standard B3"
                Case PageMediaSizeName.JISB4 : Return "Japanese Industrial Standard B4"
                Case PageMediaSizeName.JISB4Rotated : Return "Japanese Industrial Standard B4 Rotated"
                Case PageMediaSizeName.JISB5 : Return "Japanese Industrial Standard B5"
                Case PageMediaSizeName.JISB5Rotated : Return "Japanese Industrial Standard B5 Rotated"
                Case PageMediaSizeName.JISB6 : Return "Japanese Industrial Standard B6"
                Case PageMediaSizeName.JISB6Rotated : Return "Japanese Industrial Standard B6 Rotated"
                Case PageMediaSizeName.JISB7 : Return "Japanese Industrial Standard B7"
                Case PageMediaSizeName.JISB8 : Return "Japanese Industrial Standard B8"
                Case PageMediaSizeName.JISB9 : Return "Japanese Industrial Standard B9"
                Case PageMediaSizeName.NorthAmerica10x11 : Return "10 x 11"
                Case PageMediaSizeName.NorthAmerica10x12 : Return "10 x 12"
                Case PageMediaSizeName.NorthAmerica10x14 : Return "10 x 14"
                Case PageMediaSizeName.NorthAmerica11x17 : Return "11 x 17"
                Case PageMediaSizeName.NorthAmerica14x17 : Return "14 x 17"
                Case PageMediaSizeName.NorthAmerica4x6 : Return "4 x 6"
                Case PageMediaSizeName.NorthAmerica4x8 : Return "4 x 8"
                Case PageMediaSizeName.NorthAmerica5x7 : Return "5 x 7"
                Case PageMediaSizeName.NorthAmerica8x10 : Return "8 x 10"
                Case PageMediaSizeName.NorthAmerica9x11 : Return "9 x 11"
                Case PageMediaSizeName.NorthAmericaArchitectureASheet : Return "Architecture A Sheet"
                Case PageMediaSizeName.NorthAmericaArchitectureBSheet : Return "Architecture B Sheet"
                Case PageMediaSizeName.NorthAmericaArchitectureCSheet : Return "Architecture C Sheet"
                Case PageMediaSizeName.NorthAmericaArchitectureDSheet : Return "Architecture D Sheet"
                Case PageMediaSizeName.NorthAmericaArchitectureESheet : Return "Architecture E Sheet"
                Case PageMediaSizeName.NorthAmericaCSheet : Return "C Sheet"
                Case PageMediaSizeName.NorthAmericaDSheet : Return "D Sheet"
                Case PageMediaSizeName.NorthAmericaESheet : Return "E Sheet"
                Case PageMediaSizeName.NorthAmericaExecutive : Return "Executive"
                Case PageMediaSizeName.NorthAmericaGermanLegalFanfold : Return "German Legal Fanfold"
                Case PageMediaSizeName.NorthAmericaGermanStandardFanfold : Return "German Standard Fanfold"
                Case PageMediaSizeName.NorthAmericaLegal : Return "Legal"
                Case PageMediaSizeName.NorthAmericaLegalExtra : Return "Legal Extra"
                Case PageMediaSizeName.NorthAmericaLetter : Return "Letter"
                Case PageMediaSizeName.NorthAmericaLetterExtra : Return "Letter Extra"
                Case PageMediaSizeName.NorthAmericaLetterPlus : Return "Letter Plus"
                Case PageMediaSizeName.NorthAmericaLetterRotated : Return "Letter Rotated"
                Case PageMediaSizeName.NorthAmericaMonarchEnvelope : Return "Monarch Envelope"
                Case PageMediaSizeName.NorthAmericaNote : Return "Note"
                Case PageMediaSizeName.NorthAmericaNumber10Envelope : Return "#10 Envelope"
                Case PageMediaSizeName.NorthAmericaNumber10EnvelopeRotated : Return "#10 Envelope Rotated"
                Case PageMediaSizeName.NorthAmericaNumber11Envelope : Return "#11 Envelope"
                Case PageMediaSizeName.NorthAmericaNumber12Envelope : Return "#12 Envelope"
                Case PageMediaSizeName.NorthAmericaNumber14Envelope : Return "#14 Envelope"
                Case PageMediaSizeName.NorthAmericaNumber9Envelope : Return "#9 Envelope"
                Case PageMediaSizeName.NorthAmericaPersonalEnvelope : Return "Personal Envelope"
                Case PageMediaSizeName.NorthAmericaQuarto : Return "Quarto"
                Case PageMediaSizeName.NorthAmericaStatement : Return "Statement"
                Case PageMediaSizeName.NorthAmericaSuperA : Return "Super A"
                Case PageMediaSizeName.NorthAmericaSuperB : Return "Super B"
                Case PageMediaSizeName.NorthAmericaTabloid : Return "Tabloid"
                Case PageMediaSizeName.NorthAmericaTabloidExtra : Return "Tabloid Extra"
                Case PageMediaSizeName.OtherMetricA3Plus : Return "A3 Plus"
                Case PageMediaSizeName.OtherMetricA4Plus : Return "A4 Plus"
                Case PageMediaSizeName.OtherMetricFolio : Return "Folio"
                Case PageMediaSizeName.OtherMetricInviteEnvelope : Return "Invite Envelope"
                Case PageMediaSizeName.OtherMetricItalianEnvelope : Return "Italian Envelope"
                Case PageMediaSizeName.PRC10Envelope : Return "People's Republic of China #10 Envelope"
                Case PageMediaSizeName.PRC10EnvelopeRotated : Return "People's Republic of China #10 Envelope Rotated"
                Case PageMediaSizeName.PRC16K : Return "People's Republic of China 16K"
                Case PageMediaSizeName.PRC16KRotated : Return "People's Republic of China 16K Rotated"
                Case PageMediaSizeName.PRC1Envelope : Return "People's Republic of China #1 Envelope"
                Case PageMediaSizeName.PRC1EnvelopeRotated : Return "People's Republic of China #1 Envelope Rotated"
                Case PageMediaSizeName.PRC2Envelope : Return "People's Republic of China #2 Envelope"
                Case PageMediaSizeName.PRC2EnvelopeRotated : Return "People's Republic of China #2 Envelope Rotated"
                Case PageMediaSizeName.PRC32K : Return "People's Republic of China 32K"
                Case PageMediaSizeName.PRC32KBig : Return "People's Republic of China 32K Big"
                Case PageMediaSizeName.PRC32KRotated : Return "People's Republic of China 32K Rotated"
                Case PageMediaSizeName.PRC3Envelope : Return "People's Republic of China #3 Envelope"
                Case PageMediaSizeName.PRC3EnvelopeRotated : Return "People's Republic of China #3 Envelope Rotated"
                Case PageMediaSizeName.PRC4Envelope : Return "People's Republic of China #4 Envelope"
                Case PageMediaSizeName.PRC4EnvelopeRotated : Return "People's Republic of China #4 Envelope Rotated"
                Case PageMediaSizeName.PRC5Envelope : Return "People's Republic of China #5 Envelope"
                Case PageMediaSizeName.PRC5EnvelopeRotated : Return "People's Republic of China #5 Envelope Rotated"
                Case PageMediaSizeName.PRC6Envelope : Return "People's Republic of China #6 Envelope"
                Case PageMediaSizeName.PRC6EnvelopeRotated : Return "People's Republic of China #6 Envelope Rotated"
                Case PageMediaSizeName.PRC7Envelope : Return "People's Republic of China #7 Envelope"
                Case PageMediaSizeName.PRC7EnvelopeRotated : Return "People's Republic of China #7 Envelope Rotated"
                Case PageMediaSizeName.PRC8Envelope : Return "People's Republic of China #8 Envelope"
                Case PageMediaSizeName.PRC8EnvelopeRotated : Return "People's Republic of China #8 Envelope Rotated"
                Case PageMediaSizeName.PRC9Envelope : Return "People's Republic of China #9 Envelope"
                Case PageMediaSizeName.PRC9EnvelopeRotated : Return "People's Republic of China #9 Envelope Rotated"
                Case PageMediaSizeName.Roll04Inch : Return "4-inch wide roll"
                Case PageMediaSizeName.Roll06Inch : Return "6-inch wide roll"
                Case PageMediaSizeName.Roll08Inch : Return "8-inch wide roll"
                Case PageMediaSizeName.Roll12Inch : Return "12-inch wide roll"
                Case PageMediaSizeName.Roll15Inch : Return "15-inch wide roll"
                Case PageMediaSizeName.Roll18Inch : Return "18-inch wide roll"
                Case PageMediaSizeName.Roll22Inch : Return "22-inch wide roll"
                Case PageMediaSizeName.Roll24Inch : Return "24-inch wide roll"
                Case PageMediaSizeName.Roll30Inch : Return "30-inch wide roll"
                Case PageMediaSizeName.Roll36Inch : Return "36-inch wide roll"
                Case PageMediaSizeName.Roll54Inch : Return "54-inch wide roll"
                Case PageMediaSizeName.Unknown : Return "Unknown paper size"
                Case Else
#If DEBUG Then
                    Throw New NotImplementedException(String.Format("{0} ""{1}"" not implemented!", pMediaSize.GetType.Name, pMediaSize.ToString))
#End If
                    Return pMediaSize.ToString
            End Select
        End Function

    End Class

End Namespace