Option Strict Off
Option Explicit On
Imports System.IO
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")>
<System.SerializableAttribute()>
<System.Diagnostics.DebuggerStepThroughAttribute()>
<System.ComponentModel.DesignerCategoryAttribute("code")>
<System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True)>
<System.Xml.Serialization.XmlRootAttribute([Namespace]:="", IsNullable:=False)>
Partial Public Class ValidityCheckContainer

    Private creatorField As String

    Private dateOfCreationField As Date

    Private projectField As String

    Private partNumberField As String

    Private versionField As String

    Private validityCheckEntryField() As ValidityCheckEntry

    '''<remarks/>
    Public Property Creator() As String
        Get
            Return Me.creatorField
        End Get
        Set
            Me.creatorField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property DateOfCreation() As Date
        Get
            Return Me.dateOfCreationField
        End Get
        Set
            Me.dateOfCreationField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property Project() As String
        Get
            Return Me.projectField
        End Get
        Set
            Me.projectField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property PartNumber() As String
        Get
            Return Me.partNumberField
        End Get
        Set
            Me.partNumberField = Value
        End Set
    End Property

    '''<remarks/>
    Public Property Version() As String
        Get
            Return Me.versionField
        End Get
        Set
            Me.versionField = Value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("ValidityCheckEntry")>
    Public Property ValidityCheckEntries() As ValidityCheckEntry()
        Get
            Return Me.validityCheckEntryField
        End Get
        Set
            Me.validityCheckEntryField = Value
        End Set
    End Property

    Public Shared Function LoadFromFile(fullName As String) As ValidityCheckContainer
        Using xmlStream As New FileStream(fullName, FileMode.Open, FileAccess.Read)
            Return Load(xmlStream)
        End Using
    End Function

    Public Shared Function Load(s As System.IO.Stream) As ValidityCheckContainer
        Using xmlReader = Xml.XmlReader.Create(s)
            Dim serializer = New Xml.Serialization.XmlSerializer(GetType(ValidityCheckContainer))
            Return DirectCast(serializer.Deserialize(xmlReader), ValidityCheckContainer)
        End Using
    End Function

End Class

